import { useEffect, useState } from "react";
import "./cancionero.css";
import Footer from "../components/footer.jsx";

const Cancionero = () => {
  const [currentPage, setCurrentPage] = useState(1);
  const [llave, setLlave] = useState(false);
  const [letra, setLetra] = useState([]);
  const [tituloCancionSeleccionada, setTituloCancionSeleccionada] = useState("");
  const [busqueda, setBusqueda] = useState(""); // Estado para la cadena de búsqueda
  const [resultadoBusqueda, setResultadoBusqueda] = useState([]); // Estado para almacenar el resultado de la búsqueda
  const canciones = [
{"id":"1","titulo": "A Dios sea la gloria","letra":"A Dios sea la gloria, al mundo El dió\nAl Hijo Bendito, que por nos murió;\nExpió los pecados de quien en El cree,\nAbriónos la senda hacia Dios por la fe.\n\n/es\n¡Gloria a Dios!¡Gloria a Dios!\nQue de tal modo amó\nAl que lejos de El\nEn pecado se halló.\nVenid por el hijo al gran Dios Salvador,\nY dadle la gloria por tan grande amor.\n\n/est\nLa sangre de Cristo la obra efectuó,\nPara todo creyente perdón alcanzó;\nSi en Cristo confía el más vil pecador,\nPerdón en el acto le otorga el Señor.\n\n/es\n¡Gloria a Dios!¡Gloria a Dios!\nQue de tal modo amó\nAl que lejos de El\nEn pecado se halló.\nVenid por el hijo al gran Dios Salvador,\nY dadle la gloria por tan grande amor."},
{"id":"2","titulo":"A quien iré en necesidad?","letra":"¿A quién iré en necesidad?\r\n¿A quién iré en busca de paz?\r\nY ¿quién podrá mi vida saciar de verdad?\r\n¿Quién más tendrá de mi compasión,\r\ny entenderá mi corazón?\r\n¿Quién cambiará mi eternidad, \r\nsino Tu, Jesús?\r\n\r\nCristo, ¿a dónde más podría ir?\r\nCristo, ¿qué otro lugar puede existir?\r\nSólo Tu tienes palabras de amor,\r\ncamino al Padre y verdad eres Tu"},
{"id":"3","titulo":"A ti la gloria!","letra":"¡A ti la gloria, oh nuestro Señor! \r\nA ti la victoria, gran Libertador.\r\nTe alzaste pujante, lleno de poder, \r\nmás que el sol radiante al amanecer.\r\n\r\n¡A ti la gloria, oh nuestro Señor! \r\n¡A ti la victoria, gran Libertador!\r\n\r\nLibre de pena, nuestro Rey Jesús, \r\nrompe las cadenas de la esclavitud.\r\nQuien muera al pecado, en Dios vivirá, \r\nha resucitado, ya no morirá.\r\n\r\nGozo, alegría reinen por doquier, \r\nporque Cristo hoy día, muestra su poder.\r\nVanle aclamando como vencedor, \r\nángeles cantando himnos al Señor."},
{"id":"4","titulo":"A Ti, el alfa y la omega, el principio y el fin","letra":"A Ti, el alfa y la omega, el principio y el fin,\r\ny el gran Yo Soy, me rindo.\r\nA Ti, el Todopoderoso, el que es y que será\r\ny el gran Yo Soy, me entrego.\r\n\r\n\/\/ Yo quiero que gobiernes mi vida, \r\nme doy en sacrificio a Ti.\r\nYo quiero que Tú ordenes mi caminar, \r\nque siempre viva en tu voluntad. \/\/"},
{"id":"5","titulo":"A tus pies","letra":"A Tus pies, arde mi corazón\r\nA Tus pies, entrego lo que soy\r\nEse lugar de mi seguridad\r\nDonde nadie me puede señalar\r\n\r\nMe perdonaste\r\nMe acercaste a Tu presencia\r\nMe levantaste\r\nHoy me postro a adorarte\r\n\r\nNo hay lugar más alto, más grande\r\nQue estar a Tus pies, que estar a Tus pies\r\nNo hay lugar más alto, más grande\r\nQue estar a Tus pies, que estar a Tus pies\r\n\r\nA Tus pies, arde mi corazón\r\nA Tus pies, entrego lo que soy\r\nEse lugar de mi seguridad\r\nDonde nadie me puede señalar\r\n\r\nMe perdonaste\r\nMe acercaste a Tu presencia\r\nMe levantaste\r\nHoy me postro a adorarte\r\n\r\nNo hay lugar más alto, más grande\r\nQue estar a Tus pies, estar a Tus pies\r\nNo hay lugar más alto, más grande\r\nQue estar a Tus pies, estar a Tus pies\r\n\r\n\/Y aquí permaneceré\r\nPostrado a Tus pies\r\nY aquí permaneceré\r\nA los pies de Cristo\/\r\n\r\nNo hay lugar más alto, más grande\r\nQue estar a Tus pies, que estar a Tus pies\r\nNo hay lugar más alto, más grande\r\nQue estar a Tus pies, estar a Tus pies"},
{"id":"6","titulo":"Abre mis ojos, oh Cristo","letra":"Salmos 8: 1\r\n\r\nAbre mis ojos, oh Cristo.\r\nAbre mis ojos, Señor.\r\nYo quiero verte, yo quiero verte.\r\n\r\nAl contemplar tu majestad\r\nY el resplandor de tu gloria\r\nDerrama tu amor y poder\r\nMientras cantamos Santo Santo\r\n\r\nSanto, Santo, Santo (3 veces)\r\nYo quiero verte"},
{"id":"7","titulo":"Abre mis ojos, quiero ver a Cristo","letra":"Abre mis ojos, quiero ver a Cristo, \r\ny contemplarle, decirle: Te amo.\r\nAbre mi oído, ayúdame a oírle, \r\nabre mi corazón, para conocerle."},
{"id":"8","titulo":"Adoramos por siempre al Creador","letra":"Adoramos por siempre al Creador, \r\na Ti Señor, alzamos hoy la voz.\r\nTu nombre Santo es, tu nombre Santo es.\r\n\r\nCuan santo eres Tú, Santa Trinidad, \r\nRey de reyes y el Señor.\r\nTu nombre es, tu nombre es, \r\ntu nombre Santo es."},
{"id":"9","titulo":"Al Cordero de Dios sea la gloria","letra":"Al Cordero de Dios sea la gloria, \r\nal Cordero de Dios sea la honra,\r\npor su muerte en la cruz, \r\npor su sangre vertida por mí.\r\nGloria al Cordero de Dios."},
{"id":"10","titulo":"Al Cordero que murió ","letra":"Al Cordero que murió \r\ny está sentado en majestad,\r\npor su grande redención \r\ny por su eterna dignidad.\r\nTodo el honor, fortaleza y gloria, \r\ntodo el poder y nuestro amor.\r\n\r\nEres el Señor, eres el Señor.\r\nEres el Señor, eres el Señor."},
{"id":"11","titulo":"Al entrar a tu santo lugar","letra":"Al entrar a tu santo lugar,\r\nme asombra que me pueda acercar\r\npara ver tu gloria y tu belleza\r\ny adorarte en intimidad.\r\n\r\nEn confianza yo me puedo acercar,\r\nde tu mesa quiero participar,\r\ntodo lo que puedo hacer es postrarme\r\ny con mis labios proclamar.\r\n\r\nMi pan, mi luz, mi oración, eres tu Jesús. \r\nMi Dios, mi amor y mi canción, eres tu Jesús, sólo Tu.\r\n\r\n\/Me cuidas, me abrazas, me cantas, me amas.\/"},
{"id":"12","titulo":"Al estar en la presencia de tu divinidad","letra":"Al estar en la presencia de tu divinidad,\r\nal contemplar la hermosura de tu santidad.\r\nMi espíritu se alegra en tu majestad. \r\nTe adoro a Ti, te adoro a Ti.\r\nCuando veo la grandeza de tu dulce amor,\r\ny compruebo la pureza de tu corazón.\r\nMi espíritu se alegra en tu majestad. \r\nTe adoro a Ti, te adoro a Ti.\r\n\r\nY al estar aquí delante de Ti te adoraré.\r\nPostrado ante Ti, mi corazón te adora oh Dios.\r\nY siempre quiero estar \r\npara adorarte y contemplar tu santidad. \r\nTe adoro a Ti Señor, te adoro a Ti."},
{"id":"13","titulo":"Al Señor Jesús loemos ","letra":"Al Señor Jesús loemos \r\nPorque tanto le debemos,\r\nLo que somos y tenemos \r\nSólo es nuestro en Él.\r\n\r\nEs Jesús su nombre amado,\r\nA su pueblo El ha salvado;\r\nEs el triunfo asegurado\r\nPor su gran poder.\r\n\r\n¡Oh, confiad en este amigo!\r\nNos liberta del peligro,\r\nNos es hoy un fuerte abrigo\r\nY hasta el fin será.\r\n\r\nCumpliráse nuestro anhelo,\r\nEn el día en que sin velo\r\nLe veremos en el cielo-\r\nAl Señor Jesús."},
{"id":"14","titulo":"Al único que es digno de recibir ","letra":"1ªTimoteo 1:17\r\n\r\nAl único que es digno de recibir \r\nhonra y gloria, fuerza y poder.\r\nAl Dios y Padre eternal, \r\ninvisible pero real, a Él hoy ministramos loor.\r\n\r\nTe coronamos Señor y Rey Jesús. \r\nTe coronamos Señor y Rey Jesús.\r\nAdoramos tu nombre, nos rendimos a tus pies,\r\nconsagramos todo nuestro ser a Ti.\r\nConsagramos todo nuestro ser a Ti.\r\nConsagramos todo nuestro ser a Ti."},
{"id":"15","titulo":"Alabado sea tu nombre ","letra":"Alabado sea tu nombre \r\nporque Tú nos has marcado el camino,\r\nalabado sea tu nombre, \r\npor tu gracia hoy podemos amarte.\r\n\r\nTú nos diste vida, \r\ny no es cualquier vida,\r\nes eterna porque Tú eres eterno. \r\nAlabado sea tu nombre."},
{"id":"16","titulo":"Alabanzas, alabanzas sean ","letra":"Alabanzas, alabanzas sean \r\nelevadas a nuestro Señor.\r\nAlabanzas, alabanzas sean \r\nelevadas a nuestro Señor.\r\nAlabanzas puras, alabanzas santas.\r\nAlabanzas, alabanzas sean \r\nelevadas a nuestro Señor."},
{"id":"17","titulo":"Aleluya el Señor está aquí ","letra":"Aleluya el Señor está aquí \r\ny su presencia por siempre en nosotros está.\r\nAleluya el Señor está aquí \r\ny su presencia por siempre en nosotros está.\r\nAlabadle por su grandeza, \r\ndadle gloria por sus proezas,\r\npor su hermosura y santidad."},
{"id":"18","titulo":"Aleluya, aleluya nuestro Dios Poderoso es Rey","letra":"Aleluya, aleluya nuestro Dios Poderoso es Rey.\r\nAleluya, aleluya.\r\n\r\nSanto Santo, eres Tu Dios Poderoso Rey.\r\nDigno eres Tú, Cordero de Dios, eres Santo."},
{"id":"19","titulo":"Amado Jesucristo","letra":"Amado Jesucristo,\r\nsólo Tu eres digno,\r\nde gloria y de honor.\r\nTe coronamos Rey y Señor.\r\n\r\nTe damos alabanzas,\r\nsoberano Salvador.\r\nDe corazones puros\r\nrecibe esta ofrenda de amor."},
{"id":"20","titulo":"Aquel que la buena obra empezó","letra":"Filipenses 1:6\r\n\r\nAquel que la buena obra empezó, \r\naquel que la buena obra empezó,\r\nserá fiel en completarla, \r\nÉl es fiel en completarla.\r\nEl que la comenzó \r\nserá fiel en completarla en ti."},
{"id":"21","titulo":"Aquí estás Te vemos mover","letra":"\/Aquí estás Te vemos mover\nTe adoraré, Te adoraré\nAquí estás Obrando en mí\nTe adoraré, Te adoraré\/\n\n\/ Milagroso, abres camino\nCumples promesas Luz en tinieblas\nMi Dios, así eres Tú \/\n\nAquí estás Sanando mi corazón\nTe adoraré, Te adoraré\nAquí estás Tocando mi corazón\nTe adoraré, Te adoraré\n\n\/Milagroso, abres camino Cumples promesas\nLuz en tinieblas. Mi Dios, así eres Tú\/\n\nAquí estás, Tocando mi corazón\nTe adoraré, Te adoraré\n\nAquí estás, Sanando mi corazón\nTe adoraré, Te adoraré.\n\n(Hoy y siempre, Te llamamos)\nMilagroso, abres camino\nCumples promesas\nLuz en tinieblas\nMi Dios, así eres Tú\n\nMilagroso, abres camino\nCumples promesas\nLuz en tinieblas\nMi Dios, así eres Tú\n\nAsí eres Tú (así eres Tú)\nAsí eres Tú (así eres Tú)\nAsí eres Tú (así eres Tú)\nAsí eres Tú (así eres Tú)\n\n\/\/Aunque no pueda ver, estás obrando\nAunque no pueda ver, estás obrando\nSiempre estás, siempre estás obrando\nSiempre estás, siempre estás obrando\/\/\n\n\/Milagroso, abres camino\nCumples promesas\nLuz en tinieblas\nMi Dios, así eres Tú\/\n\nSolo así eres Tú (así eres Tú)\nAsí eres Tú (así eres Tú)\nAsí eres Tú (así eres Tú)\nAsí eres Tú (así eres Tú)"},
{"id":"22","titulo":"Aqui estoy rendido por tu majestad","letra":"Aqui estoy rendido por tu majestad,\r\ncubierto por tu gracia Señor.\r\nAqui estoy, sabiendo que soy un pecador\r\ncubierto por tu sangre señor\r\n\r\nEncontré el mas inmenso amor por mi,\r\ntu vida entregaste, en el Gran Sacrificio.\r\n\r\nMajestad, Majestad\r\ntu gracia me encontró tal cual soy\r\nno era nada y tu me diste valor.\r\n\r\nAqui estoy, rendido por tu amor que me das,\r\ntu perdon me hace perdonar.\r\nAqui estoy, se que tu deseo soy\r\nSanto por gloria y poder.\r\n\r\nEncontré el mas inmenso amor por mi,\r\ntu vida entregaste, en el Gran Sacrificio.\r\n\r\nMajestad, Majestad\r\ntu gracia me encontró tal cual soy\r\nno era nada\r\ny tu me diste valor\r\n\r\nMajestad, Majestad\r\ntu amor me cambia al habitar\r\nen presencia de tu majestad.\r\n(se repite coro 1 vez)"},
{"id":"23","titulo":"Atráeme a Ti, no me dejes ir","letra":"Atráeme a Ti, no me dejes ir.\r\nLo rindo todo una vez más\r\na cambio de tu amistad.\r\nYo te anhelo a Ti, solamente a Ti.\r\nPues nadie más en tu lugar,\r\nme abrazará con tanto amor.\r\nGuíame Señor de regreso a Ti.\r\n\r\n\/Te anhelo a Ti, Señor te necesito.\r\nTe anhelo a Ti, dime que cerca estás.\/"},
{"id":"24","titulo":"Aún antes de hablar, tu voz podía oír","letra":"Aún antes de hablar, tu voz podía oír\r\nHas sido tan bueno para mí\r\nAntes de respirar, soplaste tu aliento en mí\r\nHas sido tan bueno para mí\r\n\r\nTu amor me envuelve, me sostiene\r\nAmor sin condición\r\nMe persigue y deja, las noventa y nueve\r\nY va por mí\r\n\r\nNo puedo ganarlo, ni merecerlo\r\nTu amor se entregó por mí\r\nTu amor me envuelve, me sostiene\r\nAmor sin condición\r\n\r\nCuando enemigo fui\r\nTu amor luchó por mí\r\nHas sido tan bueno para mí\r\nCuando indigno fui\r\nPagaste el precio por mí\r\nHas sido tan bueno para mí\r\n\r\nTu amor me envuelve, me sostiene\r\nAmor sin condición\r\nMe persigue y deja las noventa y nueve\r\nY va por mí\r\n\r\nNo puedo ganarlo, ni merecerlo\r\nTu amor se entregó por mí\r\nTu amor me envuelve, me sostiene\r\nAmor sin condición, ¡yeah!\r\n\r\n\/No hay sombra que no alumbres\r\nMonte que no escales\r\nPara encontrarme a mí\r\nNo hay pared que no derrumbes\r\nCadena que no rompas\r\nPara encontrarme a mí\/\r\n\r\nTu amor me envuelve, me sostiene\r\nAmor sin condición\r\nMe persigue y deja las noventa y nueve\r\nY va por mí\r\n\r\nNo puedo ganarlo, ni merecerlo\r\nTu amor se entregó por mí\r\nTu amor me envuelve, me sostiene\r\nAmor sin condición"},
{"id":"25","titulo":"Bendeciré a Jehová en todo tiempo","letra":"Salmos 34: 1-4\r\n\r\nBendeciré a Jehová en todo tiempo, \r\nsu alabanza en mi boca estará.\r\nEn Jehová se gloriará mi alma, \r\nlo oirán los mansos y se alegrarán.\r\nEngrandeced a Jehová conmigo \r\ny exaltemos a una su nombre.\r\nBusqué a Jehová y el me oyó \r\ny de todos mis temores me libró."},
{"id":"26","titulo":"Brillemos en un mundo que vive sin luz.","letra":"Brillemos en un mundo que vive sin luz.\r\nMostremos el amor que nos dejó Jesús.\r\nLlevemos vida y esperanza.\r\nPodrán hallar en Dios confianza.\r\nBrillemos en un mundo que vive sin luz."},
{"id":"27","titulo":"Bueno es alabar oh Señor, tu nombre","letra":"Bueno es alabar oh Señor, tu nombre.\r\nDarte gloria, honra y honor, por siempre.\r\nBueno es alabarte Jesús, \r\ny gloriarme en tu poder.\r\n\r\n\/ Porque grande eres Tu, \r\ngrandes son tus obras.\r\nPorque grande eres Tu, \r\ngrande es tu amor, grande es tu gloria.\/\r\n\r\nBueno es alabarte Señor."},
{"id":"28","titulo":"Bueno es alabarte, oh Jehová","letra":"Salmos 92:1\r\n\r\nBueno es alabarte, oh Jehová,\r\ny cantar salmos a tu nombre.\r\nOh Altísimo. Salmos 92:1."},
{"id":"29","titulo":"Buscas caminos sin saber","letra":"Buscas caminos sin saber, \r\nbuscas salidas a tu ser,\r\npero no encuentras la verdad.\r\nBuscas en vicios y no hallas, \r\npedís consejos no te dan,\r\nte sentís solo y no querés hablar.\r\n\r\nPero hoy te vengo a decir \r\nlo que hizo Cristo en mí.\r\nUna nueva vida Él me dio, \r\ny ahora feliz estoy.\r\n\r\nSi querés encontrar la paz, \r\ntenés que reconocer \r\nque no sos nada sin Jesús.\r\nEn una cruz por ti Él murió, \r\ny su sangre derramó por salvarte a vos."},
{"id":"30","titulo":"Cada cosa en la vida, tiene su justo lugar","letra":"Eclesiastés 3:1-8\r\n\r\nCada cosa en la vida, tiene su justo lugar,\r\ncada cosa tiene un tiempo \r\npara hacerse realidad.\r\nEs por eso que preciso \r\nque me enseñes a mirar,\r\nlo que tengo por delante \r\ny el presente que esta acá.\r\n\r\nEnséñame a vivir el hoy de tal manera,\r\nque mañana, \r\nno tenga que reprocharme el ayer.\r\nEnséñame a vivir el hoy de tal manera,\r\nque mañana, \r\nno tenga que reprocharme el ayer. Enséñame.\r\n\r\nTiempo de nacer, tiempo de morir,\r\ntiempo de llorar, también de reír,\r\ntiempo de buscar, tiempo de perder,\r\ntiempo de saber lo que hay que hacer.\r\nEs por eso que preciso \r\nque me enseñes a vivir,\r\ny a no equivocarme cuando tenga que elegir."},
{"id":"31","titulo":"Cada día con Cristo me llena de perfecta paz","letra":"Cada día con Cristo me llena de perfecta paz,\r\ncada día con Cristo le amo más y más.\r\nÉl me salva y guarda, \r\ny sé que pronto volverá (a buscarme)\r\nY vivir con Cristo, más dulce cada día será,\r\nY vivir con Cristo, más dulce cada día será."},
{"id":"32","titulo":"Cada mañana al despertar","letra":"Cada mañana al despertar,\r\ny por la noche al descansar,\r\nagradezco tus bondades a mi vida,\r\npor todo lo que me permites disfrutar.\r\n\r\nAleluya, Aleluya, Aleluya,\r\nagradecido estoy por tu bondad."},
{"id":"33","titulo":"Celebrad a Cristo celebrad","letra":"\/\/\/\/ Celebrad a Cristo celebrad. \/\/\/\/\r\nResucitó, resucitó, y hoy vive para siempre.\r\nResucitó, resucitó, \r\n\/\/\/ vamos a celebrar \/\/\/, resucitó el Señor."},
{"id":"34","titulo":"Cerca de Ti yo quiero estar","letra":"Juan 10\r\n\r\nCerca de Ti yo quiero estar\r\npara escuchar tu voz y aprender de Ti.\r\nQuiero ser un reflejo de tu amor.\r\nYo quiero vivir sólo en tu voluntad.\r\n\r\nJesús tu eres mi buen Pastor.\r\nTu conoces mi camino,\r\nJesús puedo confiar en Ti.\r\nOh, mi Dios, me rindo hoy."},
{"id":"35","titulo":"Con humildad y sencillez ","letra":"Hechos 20: 18-21\r\n\r\nCon humildad y sencillez \r\na Ti Señor me acercaré.\r\nEs por tu amor que soy feliz\r\npara decir con todo mi corazón:\r\n\r\nTe amo a Ti no hay más que decir.\r\nMi vida es la prueba de mi amor por Ti."},
{"id":"36","titulo":"Con mis labios y mi vida  te alabo Señor, te alabo","letra":"Con mis labios y mi vida \r\nte alabo Señor, te alabo Señor.\r\nCon mis labios y mi vida \r\nte alabo bendito Señor.\r\nPorque Tú has sido precioso para mí, \r\nprecioso para mí, precioso para mí.\r\nPorque Tú has sido precioso para mí, \r\nte alabo bendito Señor."},
{"id":"37","titulo":"Con toda gloria y toda majestad","letra":"Con toda gloria y toda majestad,\r\ndiseñador del universo.\r\nDesde su trono eterno nos miró,\r\ny vino aquí como Cordero.\r\n\r\nEntre nosotros quiso caminar,\r\nbuscando al más necesitado.\r\nHasta un leproso pudo abrazar,\r\nllevó mi herida en su costado\r\n\r\nEl que lavó mis pies,\r\nsiendo Rey en su mesa me dió de comer.\r\nMe hizo caminar sobre el mar.\r\nEl único que quiero adorar.\r\n\r\nCon alto precio El nos valoró.\r\nNos dió su vida y su cansancio.\r\nEl hizo al débil fuerte en su poder,\r\ny vió en el pobre un heredero.\r\n\r\nEl que lavó mis pies,\r\nsiendo Rey en su mesa me dió de comer.\r\nMe hizo caminar sobre el mar.\r\nEl único que quiero adorar.\r\nEs Jesús, mi Rey, \r\nel que mi victoria es y es sobre todo."},
{"id":"38","titulo":"Con todo mi ser te quiero exaltar","letra":"Con todo mi ser te quiero exaltar,\r\nY decirte que te amo Señor,\r\nY que me gozo al sentir tu perdón.\r\n\r\nCon todo mi ser, te quiero exaltar, \r\nY tomarme fuerte de tu mano,\r\nY caminar contigo a todos lados.\r\n\r\n\/\/Oh, Cristo,\r\nQué hermoso es estar contigo\r\nNada se compara a ser tu amigo\r\nY tenerte dentro de mi corazón.\/\/"},
{"id":"39","titulo":"Con voz de mando y trompeta de Dios","letra":"1ra Tesalonicenses 4:16\r\n\r\nCon voz de mando y trompeta de Dios.\r\nEn los confines de la tierra se oirá la voz \r\ndel Señor.\r\n\r\nLos muertos en Cristo de sus tumbas volverán \r\ny los que vivimos en las nubes nos levantará, el Señor.\r\n\r\nY en una nube nos encontrará, \r\ny todo ojo entonces le verá.\r\nAl Cordero inmolado, a Jesús el deseado.\r\n\r\nLe veremos tal cual es \r\nen Su gloria y Su poder."},
{"id":"40","titulo":"Confío en Ti, confío en Ti.","letra":"Confío en Ti, confío en Ti.\r\nSé que tus promesas cumplirás.\r\nConfío en Ti, confío en Ti.\r\nSé que tus promesas cumpirás.\r\n\r\nEn las duras pruebas, no me dejarás,\r\ncomo el águila Tu me levantarás.\r\nSi, yo  confío en Ti,\r\nyo sólo confío en Ti."},
{"id":"41","titulo":"Conozco que todo lo puedes, que mi pensamiento no ","letra":"Job 42:2– 5\r\n\r\nConozco que todo lo puedes,\r\nque mi pensamiento no lo puedo esconder.\r\nHablaba lo que no entendía\r\ny de oídas te había oído.\r\n\r\nMas ahora mis ojos te ven,\r\nyo te preguntaré y Tú me enseñaras.\r\nMas ahora mis ojos te ven,\r\nme rindo a tus pies\r\ny me arrepiento, Señor."},
{"id":"42","titulo":"Consagrarme todo entero.","letra":"Himnario: 365\r\n\r\nConsagrarme todo entero.\r\nAlma, vida, y corazón,\r\nEs el íntimo deseo\r\nQue hoy me anima, buen Señor.\r\n\r\nHéme aquí, Señor, \r\nA tus plantas hoy,\r\nPues a ti consagrar quiero\r\nTodo lo que soy.\r\n\r\nAl contrito has prometido\r\nQue de Ti no arrojaras,\r\nHoy propicio eres conmigo\r\nY tu espíritu me das.\r\n\r\nConfesando mis pecados,\r\nQue sin número han de ser,\r\nY arrojando todo a un lado,\r\nA servirte aprenderé.\r\n\r\nMi canción constante sea,\r\nY mi sola inspiración,\r\nProclamar la dicha eterna\r\nDel que vive para Dios.\r\n\r\n¡Oh qué gozo llena mi alma \r\nAl pensar que suyo soy,\r\nY que pronto en las moradas \r\nEstaré de mi Señor!"},
{"id":"43","titulo":"Creo en Dios, Él está dentro de mí","letra":"Creo en Dios, Él está dentro de mí. \r\nCreo en Dios, desde que a Jesús yo fui.\r\nVoy a Él, cuándo le hablo en oración. \r\nTengo fe que Él escucha mi clamor.\r\n\r\nOh Señor, tú conoces mi interior, \r\nante Ti nada puedo esconder.\r\nClamo hoy, limpia este pobre ser. \r\nLléname cada día más de Ti."},
{"id":"44","titulo":"Cristo en su amor me guía, andando cada día muy ce","letra":"Cristo en su amor me guía,\r\nandando cada día muy cerca de mí.\r\nNo desespero, pues se que en el sendero\r\ntomado de su mano cuidará de mí.\r\n\r\nAunque procuren apartarme\r\ndel recto derrotero\r\npoder me infundirá su amor.\r\n\r\nOh Cristo te amo, ya ves te soy sincero,\r\nme amaste Tú primero y siempre te amaré."},
{"id":"45","titulo":"Cristo es la peña de Oreb ","letra":"Cristo es la peña de Oreb que está brotando,\r\nagua de vida saludable para ti.\r\nCristo es la peña de Oreb que está brotando,\r\nagua de vida saludable para ti.\r\n\r\nVen a beberla que es más dulce que la miel,\r\nrefresca el alma, refresca todo tu ser.\r\nCristo es la peña de Oreb que está brotando,\r\nagua de vida saludable para ti.\r\n\r\nCristo es el lirio del valle de las flores,\r\nÉl es la rosa blanca y pura de Saron.\r\nCristo es la vida y amor de los amores,\r\nÉl es la eterna fuente de la salvación."},
{"id":"46","titulo":"Cristo te exalto, Cristo te adoro ","letra":"Cristo te exalto, Cristo te adoro \r\nPorque Tú eres mi Señor.\r\nSólo a Ti daré la gloria y honor.\r\nCristo te exalto, Cristo te adoro \r\nporque Tú eres mi Señor.\r\nSólo a Ti daré la gloria y honor.\r\n\r\nGloriosa es tu presencia, \r\nme cubre y me da paz.\r\nMi ser siempre proclamará \r\nque sólo Tú eres digno, \r\nque sólo Tú eres digno,\r\nque sólo Tú eres digno de adorar."},
{"id":"47","titulo":"Cristo, salvador de nuestra vida","letra":"Cristo, salvador de nuestra vida, \r\nte coronamos hoy por siempre.\r\nCristo, Redentor y soberano, \r\nte damos toda la gloria.\r\n\r\n\/Se conmueve nuestra voz ante tanta majestad,\r\ndisfrutamos de tu amor, recibimos tu bondad.\r\nOh Cristo santo, \r\nno hay otro como Tú y hoy te amamos.\/"},
{"id":"48","titulo":"Crucificado por mí fué Jesús","letra":"Himnario: 459\r\n\r\nCrucificado por mí fué Jesús,\r\nDe tal manera me amó.\r\nSin murmurar fué llevado a la cruz,\r\nDe tal manera me amó.\r\n\r\nDe tal manera me amó,\r\nDe tal manera me amó;\r\nCristo en la cruz del calvario murió,\r\nDe tal manera me amó.\r\n\r\nEl inocente cordero de Dios,\r\nDe tal manera me amó.\r\nQue por salvarme sufrió muerte atroz,\r\nDe tal manera me amó.\r\n\r\nEn mi lugar padeció aflicción,\r\nDe tal manera me amó.\r\nYa consumó mi eternal salvación,\r\nDe tal manera me amó."},
{"id":"49","titulo":"Cuan bello es el Señor, cuan hermoso es el Señor.","letra":"Salmos 27:4\r\n\r\nCuan bello es el Señor, \r\ncuan hermoso es el Señor.\r\nCuan bello es el Señor, hoy le quiero adorar.\r\n\r\nLa belleza de mi Señor nunca se agotará.\r\nLa hermosura de mi Señor \r\nsiempre resplandecerá."},
{"id":"50","titulo":"Cuán glorioso es el cambio operado en mi ser","letra":"Cuán glorioso es el cambio operado en mi ser,\r\nViniendo a mi vida el Señor,\r\nHay en mi alma una paz que yo ansiaba tener,\r\nLa paz que me trajo su amor.\r\n\r\n\/\/El vino a mi corazón; \/\/\r\nSoy feliz con la vida que Cristo me dió,\r\nCuando él vino a mi corazón.\r\n\r\nYa no voy por la senda que el mal me trazó,\r\nDo sólo encontré confusión;\r\nMis errores pasados Jesús los borró,\r\nCuando él vino a mi corazón.\r\n\r\nNi una sombra de duda obscurece su amor,\r\nAmor que me trajo el perdón;\r\nLa esperanza que aliento la debo al Señor,\r\nPorque él vino a mi corazón."},
{"id":"51","titulo":"Cuando Cristo vino a mi corazón, mi vida entera cambió","letra":"Cuando Cristo vino a mi corazón, \r\nmi vida entera cambió.\r\nSu paz y su amor alejaron de mi \r\nlas dudas, las sombras y el temor.\r\n\r\nMi vida comenzó cuando el Señor llegó \r\ny hoy puedo cantar de su amor.\r\nMi vida comenzó cuando el Señor llegó \r\ny hoy puedo cantar de su amor.\r\n\r\nHoy quiero que Cristo te transforme a ti, \r\nque cambie tu vida también.\r\nPiensa en la cruz donde murió por ti \r\ny ábrele tu corazón."},
{"id":"52","titulo":"Cuando la trompeta del Señor se toque la final","letra":"Himnario: 155\r\n\r\nCuando la trompeta del Señor \r\nse toque la final,\r\nCon fulgor apunte el día eternal;\r\nY los redimidos suban \r\na su casa celestial,\r\nCuando allá se pase lista yo estaré.\r\n\r\nCuando allá se pase lista, \r\nCuando allá se pase lista.\r\nCuando allá se pase lista,\r\nCierto estoy que por su gracia allí estaré.\r\n\r\nCuando todas sombras huyan \r\nen la gran resurrección\r\nDe los muertos en Jesús sin corrupción,\r\nY en las nubes al Señor reciban, \r\n¡qué consolación!\r\nCuando allá se pase lista yo estaré.\r\n\r\nTrabajar es mi deseo \r\nsin cesar por el Señor,\r\nSiempre hablando de su gracia y de su amor;\r\nCuando acabe aquí mi obra \r\ny me llame el salvador,\r\nCuando allá se pase lista yo estaré."},
{"id":"53","titulo":"Cuando nadie me ve, en la intimidad","letra":"Cuando nadie me ve, en la intimidad\r\nDonde no puedo hablar más que la verdad\r\nDonde no hay apariencias\r\nDonde al descubierto queda mi corazón\r\n\r\nAllí soy sincero\r\nAllí mi apariencia de piedad se va\r\nAllí es Tu gracia lo que cuenta\r\nTu perdón lo que sustenta\r\nPara estar de pie\r\n\r\nY no podría dar la cara\r\nSi no fuera porque soy\r\nRevestido de la gracia\r\nY la justicia del Señor\r\nSi me vieran tal cual soy\r\nSe enterarían que es Jesús\r\nLo que han visto reflejado en mí\r\nTan solo fue su luz\r\n\r\nY es por Tu gracia y Tu perdón\r\nQue podemos ser llamados\r\nInstrumentos de Tu amor\r\nY es por Tu gracia y Tu perdón\r\nMi justicia queda lejos\r\nDe Tu perfección\r\n\r\nY no podría dar la cara\r\nSi no fuera porque soy\r\nRevestido de la gracia\r\nY la justicia del Señor\r\nSi me vieran tal cual soy\r\nSe enterarían que es Jesús\r\nLo que han visto reflejado en mí\r\nTan solo fue su luz\r\n\r\nY es por Tu gracia y Tu perdón\r\nQue podemos ser llamados\r\nInstrumentos de Tu amor\r\nY es por Tu gracia y Tu perdón\r\nMi justicia queda lejos\r\nDe Tu perfección"},
{"id":"54","titulo":"Cuando pienso en tu amor tan bello y te veo a Ti e","letra":"Cuando pienso en tu amor tan bello \r\ny te veo a Ti en santidad.\r\nY tú divinidad que excede las riquezas \r\nde este mundo.\r\nCuando alcanzo a tu corazón, \r\ncuando yo estoy en tu amor,\r\ncuando todo es como las sombras \r\nal lado de tu luz.\r\n\r\nTe adoro a Ti Señor Jesús, \r\nte adoro a Ti mi salvador.\r\nLa razón por la cual yo vivo es para adorarte.\r\nTe adoro a Ti Señor Jesús, \r\nte adoro a Ti mi salvador.\r\nLa razón por la cual yo vivo (será por Ti).\r\nLa razón por la cual yo vivo (será por Ti).\r\nLa razón por la cual yo vivo es para adorarte."},
{"id":"55","titulo":"Cuando te alabo arde en mí el fuego de tu Espíritu","letra":"Cuando te alabo arde en mí \r\nel fuego de tu Espíritu que inunda mi ser.\r\nNo, no, no, no callaré, no callaré,\r\ncon nuevos cantos de alabanzas te exaltaré."},
{"id":"56","titulo":"Cuando veo tu amor, cuando escucho tu verdad","letra":"Cuando veo tu amor, \r\ncuando escucho tu verdad,\r\ncuando siento tu calor y admiro tu bondad.\r\n\r\nMe deleito en Ti Señor, yo me gozo sólo en Ti.\r\nMe sustento en tu amor, \r\ny por siempre te alabaré sólo a Ti. \r\n\r\nYo me postro en tu presencia, \r\nte adoro en santidad,\r\nte bendigo con mi vida \r\ny yo quiero ofrendarme a Ti en santidad."},
{"id":"57","titulo":"Dad gracias de corazón, dad gracias al Santo Dios","letra":"2ªCorintios 8:9, Santiago 2:5\r\n\r\n\/\/ Dad gracias de corazón, \r\ndad gracias al Santo Dios.\r\nDad gracias porque ha dado al Señor Jesús. \/\/\r\n\r\n\/\/ Y ahora diga el débil fuerte soy, \r\ndiga el pobre, rico soy\r\npor lo que hizo en la cruz por mí. \/\/\r\n\r\nDad gracias."},
{"id":"58","titulo":"Damos honor a Ti","letra":"Damos honor a Ti, damos honor a Ti.\r\nCreador de vida eres Tú.\r\nDamos honor a Ti, damos honor a Ti.\r\nPorque no hay otro Dios como Tú.\r\n\r\nRey de reyes, admirable.\r\nEres el principio y fin.\r\nSoberano y sublime.\r\nEres nuestro salvador. "},
{"id":"59","titulo":"De gloria en gloria te veo","letra":"De gloria en gloria te veo. \r\nCuanto más te conozco \r\nquiero saber más de Ti.\r\nMi Dios, cual buen alfarero,\r\nquebrántame, transfórmame, \r\nmoldéame a tu imagen Señor.\r\n\/\/ Quiero ser más como Tú, \r\nver la vida como Tú,\r\nser guiado por tu espíritu \r\ny reflejar al mundo tu amor. \/\/"},
{"id":"60","titulo":"De tal manera me amó, que su vida no escatimó","letra":"De tal manera me amó,\r\nque su vida no escatimó.\r\nHasta el final el se entregó\r\ny a la muerte fue porque me amó.\r\n\r\nDe tal manera me amó,\r\nque no hay forma en que podré pagar,\r\nel precio de su grande amor,\r\npero toda mi alma quiero dar.\r\n\r\nPor su amor yo viviré.\r\nDe su amor yo cantaré.\r\nCon mi Jesús caminaré,\r\nporque El me amó a mi.\r\n\r\nPor su amor yo viviré.\r\nDe su amor yo cantaré.\r\nCon mi Jesús caminaré,\r\nporque El murió por mi.\r\nLe seguiré."},
{"id":"61","titulo":"Desde el fondo del mar","letra":"Salmos 148: Salmos 18:31\r\n\r\nDesde el fondo del mar, del más alto lugar\r\ndel mas hondo abismo\r\nte alabaré.\r\n\r\nDesde mi corazón, fuerte o débil esté\r\ncada instante de mi vida\r\ncon gozo yo diré:\r\n\r\nQue Tú eres la Roca Eterna\r\nSeñor sobre Cielo y Tierra, Tú eres Dios\r\n\r\nQue toda criatura adore\r\nque toda nación se postre\r\na Ti Señor, Tú Eres Dios."},
{"id":"62","titulo":"Desolados ya no más","letra":"Desolados ya no más Somos herederos con Jesús\r\nExtranjeros ya no más\r\nAhora somos hijos por la Cruz\r\n\r\nSomos iglesia\r\nReino de luz\r\nNuestra bandera la Cruz de Jesús\r\nSomos iglesia\r\nSomos nación\r\nLa tumba vacía es nuestra canción\r\n\r\nExtraviados ya no más\r\nNos llamas de vuelta a nuestro hogar\r\nSeparados ya no más\r\nSiempre a nuestro lado Tú estás\r\n\r\nSomos iglesia\r\nReino de luz\r\nNuestra bandera la Cruz de Jesús\r\nSomos iglesia\r\nSomos nación\r\nLa tumba vacía es nuestra canción\r\n\r\nSomos iglesia\r\nReino de luz\r\nNuestra bandera la Cruz de Jesús\r\nSomos iglesia\r\nSomos nación\r\nLa tumba vacía es nuestra canción\r\n\r\nVivo estas en gloria y honor\r\nReinas en victoria Señor\r\nNuestro ser entona a una voz\r\nCristo eres Dios, Cristo eres Dios\r\n\r\nSomos iglesia\r\nReino de luz\r\nNuestra bandera la cruz de Jesús\r\nSomos iglesia\r\nSomos nación\r\nLa tumba vacía es nuestra canción\r\n\r\nVivo estas en gloria y honor\r\nReinas en victoria Señor\r\nNuestro ser entona a una voz\r\nCristo eres Dios, Cristo eres Dios"},
{"id":"63","titulo":"Digno eres de gloria y alabanza","letra":"\/\/ Digno eres de gloria y alabanza.\r\nLevantamos nuestro canto,\r\nadorándote Señor. \/\/\r\n\r\n\/\/ Grande eres Tu, maravillas haces Tu.\r\nNo hay otro como Tu, no hay otro como Tu. \/\/"},
{"id":"64","titulo":"Digno es el Cordero Santo","letra":"Apocalipsis 4:8-11\r\n\r\nDigno es el Cordero Santo\r\nSanto, Santo es Él\r\nLevantamos nuestra alabanza\r\nal que en el trono está.\r\n\r\nSanto, Santo, Santo\r\nDios Todopoderoso\r\nquien fue, quien es y quien vendrá.\r\n\r\nLa creación hoy canta\r\ny damos gloria a Él.\r\nTú eres digno, por siempre y siempre."},
{"id":"65","titulo":"Dios está aquí","letra":"Dios esta aquí, \r\ntan cierto como el aire que respiro,\r\ntan cierto como la mañana se levanta,\r\ntan cierto como que le hablo y me puede oír.\r\n\r\nDios esta aquí, \r\ntan cierto como que un día salvó mi alma\r\ntan cierto como que su Hijo \r\nmurió por ti y por mí,\r\ntan cierto como que te llama y te espera a ti."},
{"id":"66","titulo":"Dios me abro a Ti","letra":"Juan 12: 37-43\r\n\r\nDios me abro a Ti, \r\nMe entrego a Ti, Jesús.\r\nEstoy dispuesto y en tus manos, \r\nLo rindo todo Señor.\r\n\r\nAbre mis ojos, déjame verte.\r\nQuita las vendas que me han cegado.\r\nAbre mis ojos, yo quiero verte.\r\nMuestra tu gloria y tu gran bondad.\r\n\r\nQuiero mirar tu hermosura,\r\ny contemplar tu majestad.\r\nAbre mis ojos, Jesucristo. \r\nMuestra tu gloria y tu bondad."},
{"id":"67","titulo":"Dulce refugio en la tormenta","letra":"\/\/ Dulce refugio en la tormenta\r\nes Jesucristo el salvador \r\nEl me alienta y alimenta\r\ncon su palabra y su amor. \/\/\r\n\r\nVengo a reposar en El,\r\nEl es mi amigo fiel,\r\nuna poderosa y fresca unción\r\nllenará mi corazón\r\n\r\nDulce refugio en la tormenta\r\nes Jesucristo el salvador."},
{"id":"68","titulo":"El brillo de este mundo se opaca ante Ti","letra":"El brillo de este mundo se opaca ante Ti,\r\nla gloria de esta tierra nada es.\r\nTodo cae en tu presencia oh Rey, \r\nhermosa es tu presencia, Señor.\r\n\r\n\/Tu presencia está aquí, \r\ntu presencia está en mí.\r\nY tu pueblo te recibe alabándote, \r\nhermosa es tu presencia Señor.\/"},
{"id":"69","titulo":"El Cordero que sufrió (Aquella cruz)","letra":"No se pueden crear, editar ni subir archivos … No hay suficiente espacio de almacenamiento. Obtén más ahora o quita archivos de Drive, Google Fotos o Gmail.\r\nEl Cordero que sufrió\r\nTraicionado fue\r\nEl peso de nuestra maldad\r\nFue puesto sobre Él\r\n\r\nEn silencio, soportó\r\nDolor y humillación\r\nObediente al Padre fue\r\nLa cruz, por mí, cargó\r\n\r\nEn aquella cruz, me salvaste\r\nDerramaste allí Tu amor\r\nMi alma cantará aleluya\r\nGloria y honra a Ti, Señor\r\n\r\nUnigénito de Dios\r\nViniste a redimir\r\nY perdonar a todo aquel\r\nQue se acerca a Ti\r\n\r\nEn aquella cruz, me salvaste\r\nDerramaste allí Tu amor\r\nMi alma cantará aleluya\r\nGloria y honra a Ti, Señor\r\n\r\nÉl pagó por mí, su perdón me dio\r\nPor la sangre que derramó en la cruz\r\nEl pecado ya no me puede atar\r\nLibre soy en Él, libre en verdad\r\n\r\nÉl pagó por mí, su perdón me dio\r\nPor la sangre que derramó en la cruz\r\nEl pecado ya no me puede atar\r\nLibre soy en Él, libre en verdad\r\n\r\nEn aquella cruz, me salvaste\r\nDerramaste allí Tu amor\r\nMi alma cantará aleluya\r\nGloria y honra a Ti, Señor\r\n\r\nA la muerte, Él venció\r\nLa tumba abierta está\r\nAleluya al Salvador\r\nJesús resucitó\r\n\r\nEn aquella cruz, me salvaste\r\nDerramaste allí Tu amor\r\nMi alma cantará aleluya\r\nGloria y honra a Ti, Señor\r\n\r\nGloria y honra a Ti, Señor"},
{"id":"70","titulo":"El Dios que hizo los cielos y la tierra","letra":"El Dios que hizo los cielos y la tierra\r\nCon el poder de Su palabra\r\nReina con autoridad\r\nEl Dios que aún los vientos le obedecen\r\nUna palabra es suficiente\r\nPara los muertos levantar\r\n\r\nNadie es como Él\r\nOh, gran Yo Soy\r\n\r\nTú eres el Dios que adoramos\r\nTodopoderoso y soberano\r\nGrande en misericordia y poder para salvar\r\nTú eres el Dios que adoramos\r\nQuien derrotó la muerte y el pecado\r\nGlorioso redentor y rey, te adoramos\r\n\r\nEl Dios que descendió de su trono\r\nPara llevar sobre Sus hombros\r\nNuestra culpa y transgresión\r\nJesús, exaltado sobre todo\r\nNombre sobre todo nombre\r\nSolo en Él hay salvación\r\n\r\nNadie es como Él\r\nOh, gran, Yo Soy\r\n\r\nTú eres el Dios que adoramos\r\nTodopoderoso y soberano\r\nGrande en misericordia y poder para salvar\r\nTú eres el Dios que adoramos\r\nQuien derrotó la muerte y el pecado\r\nGlorioso redentor y rey, Te adoramos\r\n\r\nA él sea la gloria y el poder\r\nTodo es de Él y para Él\r\n\r\nTú eres el Dios que adoramos\r\nTodopoderoso y soberano\r\nGrande en misericordia y poder para salvar\r\nTú eres el Dios que adoramos\r\nQuien derrotó la muerte y el pecado\r\nGlorioso redentor y rey, Te adoramos"},
{"id":"71","titulo":"Él es la voz que mis oídos abrió","letra":"Él es la voz que mis oídos abrió,\r\nLa libertad que mis cadenas rompió\r\nÉl es la luz que mi alma oscura iluminó\r\nÉl es Jesús toda mi vida transformo.\r\n\r\nÉl hizo cambiar mi oído en amor\r\nConvierte en alegría mi dolor.\r\nPuede transformar al mas pecador,\r\nDarle una nueva vida y perdón.\r\nEl hizo que vuelva a latir mi corazón."},
{"id":"72","titulo":"Él es mi rey ¡Oh cuánto yo le amo!","letra":"Él es mi rey ¡Oh cuánto yo le amo!\r\nÉl es mi rey, no hay otro como Él.\r\nTodo el día alabanzas yo le canto.\r\nOh aleluya, Él es mi rey."},
{"id":"73","titulo":"El mundo busqué y no pudo llenarme","letra":"El mundo busqué\r\nY no pudo llenarme\r\nNingún tesoro que pueda ganar\r\nMe saciará\r\n\r\nMás llegaste tú\r\nMe diste vida nueva\r\nY cada deseo se cumplirá\r\nAquí en tu amor\r\n\r\nOh no hay nada, nada mejor\r\nNo hay nada, nada mejor\r\nNo hay nada, nada mejor que mi Dios.\r\n\r\nVengo a ti,\r\nSin miedo y sin reservas\r\nCada fracaso has visto Señor\r\nY aún tu amigo soy.\r\n\r\nPorque el Dios de los montes,\r\nEs el Dios de los valles,\r\nNo hay lugar que me pueda alejar\r\nDe tu gracia y amor.\r\n\r\n\/Oh no hay nada, nada mejor\r\nNo hay nada, nada mejor\r\nNo hay nada, nada mejor que mi Dios\/\r\n\r\n\/Cambias lamento en danza\r\nDe cenizas traes vida\r\nCambias culpa por gloria\r\nSé que solo tú lo harás\/\r\n\r\nDe las ruinas y tumbas\r\nNacen nuevos jardines\r\nResucitas los huesos\r\nSé que solo tú lo harás,\r\nSé que solo tú lo harás.\r\n\r\n\/Oh no hay nada, nada mejor\r\nNo hay nada, nada mejor\r\nNo hay nada, nada mejor que mi Dios\/\r\n\r\nCambias lamento en danza\r\nDe cenizas traes vida\r\nCambias culpa por gloria,\r\nSé que solo tú lo harás.\r\n\r\nDe las ruinas y tumbas\r\nNacen nuevos jardines\r\nResucitas los huesos\r\nSé que solo tú lo harás\r\nSé que solo tú lo harás\r\nSé que solo tú lo harás"},
{"id":"74","titulo":"El resplandor del Rey vestido en majestad","letra":"El resplandor del Rey\r\nVestido en majestad\r\n\/\/ La tierra alegre está. \/\/\r\n\r\nCubierto está de luz,\r\nvenció la oscuridad,\r\n\/\/la tierra a su voz.\/\/\r\n\r\nCuán grande es Dios, cántale.\r\nCuán grande es Dios, y todos lo dirán:\r\nCuán grande es Dios.\r\n\r\nDía a día Él está.\r\nEl tiempo está en Él.\r\n\/\/ Principio y el fin. \/\/\r\n\r\nLa Trinidad en Dios,\r\nEl Padre, Hijo y Espíritu.\r\n\/\/ Cordero y El León. \/\/\r\n\r\nCuán grande es Dios, cántale.\r\nCuán grande es Dios,y todos lo dirán:\r\nCuán grande es Dios.\r\n\r\n\/\/Tu nombre sobre todo es,\r\nÉl es digno de alabar.\r\nY mi ser dirá:\r\ncuán grande es Dios.\/\/ \r\n\r\nCuán grande es Dios, cántale.\r\nCuán grande es Dios,y todos lo dirán:\r\nCuán grande es Dios.\r\n\r\n\/\/ Mi corazón entona la canción:\r\nCuán grande es Él,\r\nCuán grande es Él. \/\/"},
{"id":"75","titulo":"El Señor ha sido tan bueno que quiero alabar su nombre","letra":"El Señor ha sido tan bueno que \r\nquiero alabar su nombre,\r\nquiero alabar su nombre, \r\nquiero alabar su nombre.\r\nEl Señor ha sido tan bueno que \r\nquiero alabar su nombre.\r\nAlelu, alelu, aleluya."},
{"id":"76","titulo":"Él viene con poder (El cordero y el león)","letra":"Él viene con poder\r\nTodo reino lo verá\r\nCadenas romperá\r\nY todos le adorarán\r\nQuién como el Señor Dios fuerte.\r\n\r\nÉl es el León, León de Judá\r\nÉl tiene poder para liberar\r\nTodos se postrarán ante ti\r\nÉl es el Cordero, Cordero inmolado\r\nSu sangre en la cruz borró mi pecado\r\nTodos se postrarán ante el Cordero y el León\r\nTodos se postrarán ante ti\r\n\r\nAbrid las puertas hoy\r\nAl rey de reyes y Señor\r\nEl Dios de salvación\r\nVino a darnos libertad\r\nQuién como el Señor Dios fuerte.\r\n\r\nÉl es el León, León de Judá\r\nÉl tiene poder para liberar\r\nTodos se postrarán ante ti\r\nÉl es el Cordero, Cordero inmolado\r\nSu sangre en la cruz borró mi pecado\r\nTodos se postrarán ante el Cordero y el León\r\nTodos se postrarán ante ti.\r\n\r\n\/\/Quién como el Señor Dios fuerte\r\nQuién como el Señor Dios fuerte\/\/\r\nQuién como el Señor\r\n\r\nÉl es el León, León de Judá\r\nÉl tiene poder para liberar\r\nTodos se postrarán ante ti\r\nÉl es el Cordero, Cordero inmolado\r\nSu sangre en la cruz borró mi pecado\r\nTodos se postrarán ante el Cordero y el León\r\nTodos se postrarán ante ti"},
{"id":"77","titulo":"En Él encuentro plena paz","letra":"En Él encuentro plena paz, \r\ncuán grande es su gracia.\r\nMe da felicidad sin par, \r\ncuán grande es su amor.\r\n\r\nMe amó primero y me salvó \r\ny ahora en su amor estoy.\r\nBendito Cristo, eterno Señor."},
{"id":"78","titulo":"En el monte Calvario estaba una cruz (Himnario: 466)","letra":"Himnario: 466\r\n\r\nEn el monte Calvario estaba una cruz.\r\nde afrenta y dolor.\r\nMas yo amo a Jesús, que murió en la cruz \r\nPor salvar al más vil pecador.\r\n\r\nGloriaréme sólo en la cruz,\r\nEn sus triunfos mi gozo será;\r\nY en el día de eterna salud\r\nMi corona Jesús me dará.\r\n\r\nY aunque el mundo desprecie la cruz de Jesús\r\nPara mí tiene suma atracción:\r\nPues en ella llevó el cordero de Dios\r\n De mi alma la condenación.\r\n\r\nEn la cruz de Jesús do su sangre vertió,\r\nHermosura contemplo sin par;\r\nPues en ella triunfante a la muerte venció,\r\nY mi ser puede santificar.\r\n\r\nYo quisiera seguir en pos de Jesús,\r\nY su menosprecio llevar;\r\nY algún día feliz con los santos en luz,\r\nEn la gloria con El he de estar."},
{"id":"79","titulo":"En este día feliz, en este santo lugar","letra":"En este día feliz, en este santo lugar,\r\nquiero tener un encuentro con Dios.\r\nSu amor es real y su paz gozaré, \r\nquiero tener un encuentro con Dios.\r\n\r\nQuiero tener un encuentro con Dios \r\nen este santo lugar de oración.\r\nSu amor es real y su paz gozaré, \r\nquiero tener un encuentro con Dios."},
{"id":"80","titulo":"En la oscuridad En la tempestad (ruinas gloriosas)","letra":"En la oscuridad \r\nEn la tempestad\r\nTú me cuidas\r\nEn dificultad\r\nMe levantaré\r\nEn tu gracia\r\n\r\nPor el fuego andaré\r\nY no me quemaré\r\nTu espíritu aviva mi alma\r\nA la cruz miraré\r\nMi temor dejaré\r\nEn la luz de tu gracia señor\r\n\r\nLo que seco y muerto está\r\nTú levantas con poder\r\nY restauras las ruinas\r\nDios por siempre eres rey\r\nMi refugio encuentro\r\nEn la sombra de tu amor\r\nSiempre quiero adorarte\r\nY amarte señor\r\n\r\nAun en el dolor\r\nMi esperanza está\r\nEn tu promesa\r\nCuando débil soy\r\nTu poder me da\r\nNuevas fuerzas\r\n\r\nPor el fuego andaré\r\nY no me quemaré\r\nTu espíritu aviva mi alma\r\nA la cruz miraré\r\nMi temor dejaré\r\nEn la luz de tu gracia señor\r\n\r\nLo que seco y muerto está\r\nTú levantas con poder\r\nY restauras las ruinas\r\nDios por siempre eres rey\r\nMi refugio encuentro\r\nEn la sombra de tu amor\r\nSiempre quiero adorarte\r\nY amarte señor\r\n\r\nLo que seco y muerto está\r\nTú levantas con poder\r\nY restauras las ruinas\r\nDios por siempre eres rey\r\nMi refugio encuentro\r\nEn la sombra de tu amor\r\nSiempre quiero adorarte\r\nY amarte señor"},
{"id":"81","titulo":"En presencia estar de Cristo (Himnario: 168)","letra":"Himnario: 168\r\n\r\nEn presencia estar de Cristo,\r\nVer su rostro ¿qué será?\r\nCuando al fin en pleno gozo\r\nMi alma le contemplará.\r\n\r\nCara a cara espero verle\r\nMás allá del cielo azul:\r\nCara a cara en plena gloria,\r\nYo veré al Señor Jesús.\r\n\r\nSólo tras oscuro velo\r\nHoy le puedo aquí mirar,\r\nMas ya pronto viene el día\r\nQue su gloria ha de mostrar.\r\n\r\n¡Cuánto gozo habrá con Cristo \r\nCuando no haya más dolor.\r\nCuando cesen los peligros\r\n¡Y ya estemos en su amor!\r\n\r\nCara a cara, ¡cuán glorioso \r\n¡Ha de ser así vivir!\r\n¡Ver el rostro de quien quiso\r\nnuestras almas redimir!"},
{"id":"82","titulo":"En Ti confía mi corazón, en Ti reposa mi alma","letra":"En Ti confía mi corazón, en Ti reposa mi alma.\r\nMi ser descansa en Ti, puedo ser feliz.\r\n\r\nPorque sé que estas obrando \r\ntu perfecta voluntad.\r\nEn mi vida estás obrando \r\ntu perfecta voluntad."},
{"id":"83","titulo":"Enséñame tus caminos Señor (Salmos 86:1)","letra":"Salmos 86:1\r\n\r\nEnséñame tus caminos Señor, \r\ny andaré en tu luz.\r\nDame un corazón entregado a Ti, \r\npara honrarte oh Dios.\r\n\r\nPurifícame, límpiame Señor, \r\ny líbrame de lo que impida el fluir.\r\nPurifícame, límpiame Señor, \r\ny líbrame de lo que impida el fluir de tu amor."},
{"id":"84","titulo":"Entra en la presencia de Señor con gratitud \r\ny adórale de corazón","letra":"Entra en la presencia de Señor con gratitud \r\ny adórale de corazón.\r\nEntra en la presencia de Señor con gratitud \r\ny alza tu voz con júbilo.\r\n\r\nDa gloria, y honra, y alabanzas al Señor. \r\n¡Oh Cristo! Nombre sin igual.\r\n\r\nBendito sea el Señor, Dios poderoso,\r\nQuien fue, quien es y quien tendrá.\r\nBendito sea el Señor, Dios poderoso.\r\nPor siempre reinará.\r\n\r\nPadre del cielo te adoramos.\r\nAlzamos hoy tu nombre en alto.\r\nQue tu reino se establezca en la alabanza,\r\nde tu pueblo, que declara tu poder."},
{"id":"85","titulo":"Eres alabado, eres exaltado (Dios imparable)","letra":"Eres alabado, eres exaltado\r\nTu nombre levantamos, aleluya, aleluya\r\nEres adorado te glorificamos\r\nTu nombre levantamos, aleluya, aleluya\r\n\r\nA una sola voz, nos unimos hoy\r\nTe cantamos Dios en adoración\r\n\r\n\/Dios imparable, Dios de imposibles\r\nInigualable, eres invencible\/\r\n\r\n\/No tengo temor en mi corazón, tú tienes el control\/\r\n\r\n\/ No me falta nada si te tengo a ti \/\r\n\r\nEres alabado, eres exaltado\r\nTu nombre levantamos, aleluya, aleluya\r\n\r\nA una sola voz, nos unimos hoy\r\nTe cantamos Dios en adoración\r\n\r\n\/Dios imparable, Dios de imposibles\r\nInigualable, eres invencible\/\r\n\r\n\/No tengo temor en mi corazón, tú tienes el control\/\r\n\r\n\/ No me falta nada si te tengo a ti \/\r\n\r\n\/Y yo sé quien va conmigo va por mí\r\nY quien a mis enemigos hace huir\/\r\n\r\n\/Dios imparable, Dios de imposibles\r\nInigualable, eres invencible\/\r\n\r\n\/No tengo temor en mi corazón, tú tienes el control\/\r\n\r\n\/ No me falta nada si te tengo a ti \/"},
{"id":"86","titulo":"Eres Santo, Poderoso (príncipe de paz)","letra":"Isaías 9:6\r\n\r\nEres Santo (Eres Santo), \r\nPoderoso (Poderoso)\r\nEres Digno (eres digno), \r\nde alabar (de alabar)\r\nYo te amo (yo te amo),\r\n yo te sirvo (yo te sirvo)\r\nY por siempre (y por siempre), \r\nte seguiré (te seguiré)\r\n\r\nY yo canto y alabo\r\n(Eres el Señor y de reyes Rey)\r\nA aquel que es digno\r\n(Poderoso Dios, digno Emanuel)\r\nYo le amo, le adoro\r\n(Tu el gran \"Yo soy\" quien todo creo)\r\nY me postro ante tus pies\r\n(Príncipe de paz, Cordero de Dios)\r\n\r\nY yo canto y alabo\r\n(Eres Salvador, vives hoy en mí)\r\nA Aquel que es digno\r\n(Y tu santa voz siempre nos habla de Ti)\r\nYo le amo, le adoro\r\n(Eres Alfa y Omega, Principio y fin)\r\nY me postro ante tus pies\r\n(Jesucristo, Mesías, confío en Ti)\r\n\r\nPríncipe de paz,\r\nYo mi vida entrego a Ti"},
{"id":"87","titulo":"Eres Tú, la única razón de mi adoración","letra":"Eres Tú, la única razón de mi adoración, \r\noh Jesús.\r\nEres Tú, la esperanza que anhelé tener, \r\noh Jesús,\r\n\r\nConfié en Ti, me has ayudado.\r\nTu salvación me has regalado.\r\nHoy hay gozo en mi corazón, \r\ncon mi canto te alabaré.\r\n\r\nTe alabaré, te glorificaré,\r\nte alabaré, mi buen Jesús.\r\n\r\n\/\/ En todo tiempo te alabaré.\r\nEn todo tiempo te adoraré. \/\/"},
{"id":"88","titulo":"Es más que una canción","letra":"Es más que una canción, \r\nes más que palabras,\r\nes mi corazón rendido a Ti.\r\nEs lo mejor de mi, lo que vengo a darte,\r\nya no es suficiente una canción.\r\nLo que tu me pidas, yo te quiero dar.\r\n\r\nNo vengo a pedir, no vengo a buscar,\r\nsólo vengo a darte mi ofrenda de amor.\r\nPoder conocer, tu fiel corazón\r\ny darte las gracias, mi amado Señor.\r\nHoy te vengo a bendecir, a Ti."},
{"id":"89","titulo":"Es por Ti, que juntos hoy estamos aquí","letra":"Salmos 115:1\r\n\r\nEs por Ti, que juntos hoy estamos aquí.\r\nFue Tu amor, \r\nque de la oscuridad nos sacó.\r\nA una voz, venimos hoy delante de Ti,\r\npara darte el honor.\r\n\r\n\/ No a nosotros, oh Dios,\r\nsino a Tu Nombre sea dada la gloria. \/\r\n\r\nEres Tu el motivo de nuestra adoración.\r\nLa verdad que nuestro corazón libertó.\r\nNadie más es digno del honor recibir,\r\nte lo damos a Ti.\r\n\r\nNo a nosotros, oh Dios. oh no,\r\nsino a Tu Nombre sea dada la gloria."},
{"id":"90","titulo":"Es su forma de mirar (Fidelidad)","letra":"Es su forma de mirar\r\nViendo todo, bien o mal\r\nAun así, Él cubre mi pesar\r\nPor probar su fidelidad\r\n\r\nEs la forma en que provee\r\nToda mi necesidad\r\nHasta su vida derramar\r\nPor probar su fidelidad\r\n\r\nFidelidad, su Fidelidad\r\nTan profunda, tan real\r\nEn mi vida y caminar\r\nMe basta su fidelidad\r\n\r\nEs su forma de cuidar\r\nCada paso en mi andar\r\nNo importando a donde llegará\r\nPor probar su fidelidad\r\n\r\nFidelidad, su fidelidad\r\nTan profunda, tan real\r\nEn mi vida y caminar\r\nMe basta su fidelidad\r\nMe basta su fidelidad\r\n\r\nOh, Tu fidelidad, Tu fidelidad!\r\nCada momento la veo en mi\r\nNada me falta pues todo provee\r\nGrande señor es su fidelidad\r\n\r\nFidelidad, Su fidelidad\r\nTan profunda, tan real\r\nEn mi vida y caminar\r\nMe basta su fidelidad\r\nMe basta su fidelidad"},
{"id":"91","titulo":"Es tu fidelidad tan grande, oh Padre (Himnario: 470)","letra":"Himnario: 470\r\n\r\nEs tu fidelidad tan grande, oh Padre;\r\nTú dices la verdad, descanso allí.\r\nTu luz rodea mi senda en el mundo,\r\nTu voz me anima; mi fuerza es en ti.\r\n\r\n¡Oh qué fidelidad! ¡Oh qué fidelidad!\r\nNunca me canso de darte loor.\r\nCada mañana es nueva tu gracia;\r\nInalterable es tu gran amor.\r\n\r\nLos enemigos son muy poderosos;\r\nTú eres mi Amigo, oh Dios, fuerte Adalid\r\nEn la batalla me das hoy tu ayuda;\r\nVencido no seré, confiando en ti.\r\n\r\nEn tu presencia, oh Dios, hay gran descanso,\r\nDulce consolación, perfecta paz.\r\nAl ver las glorias de Cristo el Señor\r\nLe hemos de celebrar siempre jamás."},
{"id":"92","titulo":"Esta aquí, nos gozamos porque Dios está aquí.","letra":"Esta aquí, nos gozamos porque Dios está aquí.\r\nEsta aquí, está aquí \r\n¡Aleluya nuestro Dios está aquí!\r\n\r\nEsta en mí, \r\nnos gozamos porque Dios está en mí.\r\nEsta en mí, está en mí \r\n¡Aleluya nuestro Dios está en mí!\r\n\r\nEsta en ti, \r\nnos gozamos porque Dios está en ti,\r\nesta en ti, está en ti \r\n¡Aleluya nuestro Dios está en ti!"},
{"id":"93","titulo":"Estamos reunidos aquí Señor","letra":"Estamos reunidos aquí Señor, \r\nporque hemos conocido tu amor,\r\ntraemos en nuestros labios \r\nun nuevo cántico de loor,\r\npues tu gloria a llenado este lugar. ¡Aleluya!"},
{"id":"94","titulo":"Este es mi deseo, honrarte a Ti.","letra":"Este es mi deseo, honrarte a Tí.\r\nCon toda mi vida te adoraré.\r\nCon todas mis fuerzas te adoro hoy.\r\nMi adoración eres Tu.\r\n\r\n\/ Hoy te rindo mi ser, te doy mi corazón.\r\nYo vivo para Tí.\r\nEn cada palpitar, mientras haya aliento en mi\r\nDios has tu obra en mí. \/"},
{"id":"95","titulo":"Este pueblo que has formado hoy viene a entregar","letra":"Este pueblo que has formado \r\nhoy viene a entregar,\r\nlas ofrendas de sus labios puestas en tu altar.\r\nEste pueblo es tu iglesia que viene a adorar\r\nal Único, a su Amado, al Rey de libertad.\r\n\r\nY canta ¡Hosanna, gloria aleluya!\r\nOh, Jesús amado tu amor me ha cautivado.\r\nY canta ¡Hosanna, gloria aleluya!\r\nAlabanzas hoy yo traigo a tu nombre Jesús."},
{"id":"96","titulo":"Fija tus ojos en Cristo","letra":"Fija tus ojos en Cristo \r\ntan llenos de gracia y amor.\r\nY lo terrenal sin valor será, \r\na la luz del glorioso Señor."},
{"id":"97","titulo":"Fue tan bello, fue amor","letra":"Fue tan bello, fue amor, \r\nlo que me sucedió con el Salvador.\r\nLo que yo era mi Jesús en sus manos tomó,\r\nhizo algo bello y me transformó.\r\n\r\nAlgo bello sucedió, \r\nmi pena y confusión Él comprendió.\r\nSólo pude darle a Dios mi vida tan infiel,\r\npero algo bello hizo Él en mi ser."},
{"id":"98","titulo":"Gracias Padre por ser mi pastor","letra":"Gracias Padre por ser mi pastor. \r\nCada día descubro tu amor.\r\nY aunque sin entender te quiero agradecer,\r\nera ciego más por tu amor, me hiciste ver.\r\nY hoy puedo creer."},
{"id":"99","titulo":"Gracias Padre por ser mi pastor","letra":"Gracias Padre por ser mi pastor. \r\nCada día descubro tu amor.\r\nY aunque sin entender te quiero agradecer,\r\nera ciego más por tu amor, me hiciste ver.\r\nY hoy puedo creer."},
{"id":"100","titulo":"Gracias por la cruz, Dios","letra":"Gracias por la cruz, Dios, \r\npor el precio, tu paga.\r\nMi pecado y dolor tu amor quitó,\r\ndando gracia eternal.\r\n\r\nGracias por tu amor Dios, \r\npor las manos que herí.\r\nPues tu sangre me limpió y siento al fin,\r\ntu perdón y salvación.\r\n\r\nDigno eres Señor, en tu trono estás.\r\nCoronado con poder, reinas con majestad.\r\nCristo, Hijo de Dios, exaltado Rey.\r\nMoriste en la cruz en mi lugar.\r\nDigno eres Señor."},
{"id":"101","titulo":"Hay momentos que las palabras no alcanzan","letra":"Hay momentos que las palabras no alcanzan,\r\npara decirte lo que siento por Ti Señor Jesús.\r\n\r\nYo te agradezco por todo lo que hiciste,\r\npor todo lo que haces y todo lo que harás.\r\nYo te agradezco por todo lo que hiciste,\r\npor todo lo que haces y todo lo que harás."},
{"id":"102","titulo":"Hay momentos que no deberían terminar","letra":"Hay momentos que no deberían terminar,\r\nhay segundos que tendrían que ser eternidad.\r\nCuando tu Espíritu Señor actúa dentro mío,\r\ny mi corazón estalla en adoración.\r\n\r\nTe amo mi Señor, se acaban las palabras,\r\nsólo me queda mi alma para cantarte.\r\nTe adoro mi Señor, no hay nada alrededor,\r\nsólo estamos Tú y yo,\r\nsólo estamos Tú y yo."},
{"id":"103","titulo":"Hay perdón por la sangre de Jesús","letra":"Hay perdón por la sangre de Jesús, \r\nhay perdón por su muerte en la cruz.\r\nProclamad que hay perdón, \r\npara todos hay perdón,\r\nLos que acuden al Señor Jesús."},
{"id":"104","titulo":"Hay un deseo en mi corazón de estar donde Tú estás","letra":"1ra Corintios 13\r\n\r\nHay un deseo en mi corazón de estar donde Tú estás.\r\nSe que no hay mejor lugar,\r\nquiero habitar en tu altar.\r\n\r\nHe buscado en otras cosas\r\nel amor sin encontrar.\r\nMe doy cuenta que Tu amor, \r\nmi vida llenará.\r\n\r\nPaciente y bondadoso eres \r\n(así es tu amor)\r\nTodo lo espera y lo soporta \r\n(así es tu amor)\r\nNo tiene envidia ni rencor (\r\nasí es tu amor)\r\nTu amor nunca de ser. \r\nAsí es tu amor.\r\n\r\nMe cuidas, me amas,\r\nme cubres, me abrazas.\r\nMejor que la vida es tu amor.\r\n\r\nTan alto, sublime, eterno, perfecto.\r\nMejor que la vida, es tu amor. \r\nPor mí."},
{"id":"105","titulo":"Hay una gran promesa","letra":"Mateo 5:8\r\nHay una gran promesa \r\npara los de limpio corazón.\r\nBienaventurados son \r\npues verán con sus ojos a Dios.\r\n\r\nVeré a Dios, veré a Dios, \r\niré a vivir junto con Él.\r\nVeré a Dios, veré a Dios, \r\ncon sangre Él limpió mi corazón."},
{"id":"106","titulo":"Hoy estoy alegre porque Tú me amas","letra":"Hoy estoy alegre porque Tú me amas,\r\nen mi boca hay alabanzas, \r\ny es para Ti Jesús.\r\n\r\nAlzo mis manos hacia el cielo. \r\nSi mi Jesús, tuya es mi vida.\r\nMi alma te agradece Jesús por Tus bondades,\r\ny mis ojos hoy te ven allí sentado\r\na la diestra de Jehová y que intercedes\r\npor mi vida porque Tú eres mi abogado.\r\nPorque me amas con amor, amor eterno,\r\ny Tus brazos siempre están allí extendidos,\r\nsé que escuchas mi oración y al escucharla\r\nyo te digo mi Jesús tuya es mi vida."},
{"id":"107","titulo":"Hoy proclamamos a Cristo que resucitó","letra":"Hoy proclamamos a Cristo que resucitó.\r\nCordero santo, omnipotente Hijo de Dios.\r\n\r\n\/\/ Por siempre Tú estarás, \/\/\r\n\/\/ reinando en majestad, \/\/\r\n\/\/ venimos ante Ti, \/\/ \r\npara adorarte ¡Oh Rey!"},
{"id":"108","titulo":"Humilde vengo a Ti","letra":"Humilde vengo a Ti,\r\na darte gracias hoy,\r\npor el amor que das a mi ser.\r\nHumilde vengo a Ti, \r\na darte gracias hoy,\r\npor el amor que das a mi ser.\r\nPorque Tu vienes a mi vida, \r\ny me das de tu amor.\r\nPorque tu vienes a mi vida,\r\ny me das de tu perdón.\r\nY tu Espíritu ilumina mi ser,\r\nes por eso Dios,\r\nque humilde vengo a Ti."},
{"id":"109","titulo":"Incomparable, inigualable es tu amor","letra":"Incomparable, inigualable es tu amor,\r\ny me rodea.\r\nTú me abrazaste, me sonreíste Señor,\r\na mi pecador.\r\nTu amor me alimenta,\r\ntu amor me sustenta.\r\n\r\nCelebraré tu amor todos los días.\r\nCelebraré tu gran misericordia.\r\nCelebraré tu gracia inmerecida,\r\ncelebraré tu amor.\r\n\r\nInmensurable, inagotable es tu amor,\r\ny nunca cambia.\r\nEstás conmigo y no me puedo escapar\r\naunque lo intente.\r\nTu amor es eterno,\r\ntu amor es perfecto.\r\n\r\n\/\/ Celebraré tu amor y tu misericordia \r\noh Dios, oh oh. \/\/\r\n\r\nCelebraré tu amor todos los días.\r\nCelebraré tu gran misericordia.\r\nCelebraré tu gracia inmerecida,\r\ncelebraré tu amor."},
{"id":"110","titulo":"Jamás podré entender tu gran amor","letra":"Jamás podré entender tu gran amor.\r\nTan increíble es lo que has hecho señor\r\nDejar en esa cruz tu vida por amor,\r\nno lo entiendo mas lo acepto así.\r\nPor el mundo morir, luego resucitar.\r\nVida eterna dar. \r\nGracias Señor."},
{"id":"111","titulo":"Jesucristo es el motivo de mi canción","letra":"Jesucristo es el motivo de mi canción,\r\notra razón yo no tengo porque cantar.\r\nLa melodía es Él, toda mi vida está en Él,\r\nJesucristo es el motivo de mi canción.\r\n\r\nMuchas razones para vivir, \r\nmuchas razones para morir,\r\nmuchas razones para dar amor.\r\nNo siempre se saben los porque, \r\nla vida pasa con rapidez,\r\ncada momento yo aprovecharé\r\npara darle mis canciones, \r\nofrecer mis oraciones,\r\nentregar mi vida entera al que todo me da.\r\n\r\nJesucristo es el motivo de mi canción,\r\notra razón yo no tengo porque cantar.\r\nLa melodía es Él, toda mi vida está en Él,\r\nJesucristo es el motivo de mi canción.\r\n\r\nEn una búsqueda sin cesar, \r\nyo no me canso de preguntar\r\nsobre el porque de mis canciones para Dios.\r\nPues Él conoce mi corazón \r\ny existe sólo una razón,\r\nagradecerle toda su bondad.\r\nLe daré de mis canciones\r\ny también mis ilusiones,\r\nes la forma en que puedo expresarle mi amor."},
{"id":"112","titulo":"Jesús, amado de mi alma","letra":"1ra Juan 4:19 - colosenses 1:13-14\r\n\r\n\/\/ Jesús, amado de mi alma.\r\nJesús, jamás te dejaré.\r\nMe sacaste de la oscuridad,\r\nme trajiste libertad y ahora sé:\r\nQue te amo, te necesito.\r\nMi precioso Dios, jamás te dejaré.\r\nMi Salvador, mi mejor amigo.\r\nYo te adoraré por la eternidad. \/\/ "},
{"id":"113","titulo":"Jesús, cuánto me amó","letra":"Jesús, cuánto me amó. Jesús, por mí murió.\r\nAllí en la cruz yo comprendí \r\nel gran amor de Dios.\r\n\r\nÉl me salvó y hoy voy con Él \r\ny donde voy Él va también.\r\nHoy soy feliz, Cristo es mi Rey \r\nyo cantaré sólo a Él.\r\n\r\nJesús mi Salvador. Jesús dulce canción.\r\nMi alma sosiega en tempestad \r\ne infunde dulce paz."},
{"id":"114","titulo":"Jesús, Señor de la creación","letra":"Jesús, Señor de la creación.\r\nSiendo en forma de Dios, \r\nse despojó a sí mismo.\r\nTomó la semejanza de hombre,\r\ny siendo puro y sin mancha,\r\nentre nosotros vivió.\r\nY asimismo se humilló\r\ntomando forma de siervo\r\nhasta su vida entregar\r\ny en una cruz terminar.\r\n\r\nMás Dios a lo sumo le exaltó,\r\ny su nombre engrandeció\r\npara que ante su autoridad\r\ntoda rodilla se doble\r\ny toda lengua confiese\r\nque Jesús es el Señor."},
{"id":"115","titulo":"Juntos Hoy cantamos (Por su gracia)","letra":"Juntos Hoy cantamos\r\nComo hermanos\r\nÉl nos unió\r\nHijos\r\nDe todo pueblo\r\nEste es el tiempo\r\nDe alzar la voz\r\n\r\nNo escucharé al miedo\r\nMi mirada pongo en el cielo\r\nEn tu gracia firme estoy\r\nTú me amas tal como soy\r\nValiente seré, yo sé\r\nMi esperanza está en Él\r\n\r\nCristo\r\nEl que salva\r\nLa esperanza\r\nEstá en Él\r\nCristo\r\nLuz del cielo\r\nRey eterno\r\nAmigo fiel\r\n\r\nNo escucharé al miedo\r\nMi mirada pongo en el cielo\r\nEn tu gracia firme estoy\r\nTú me amas tal como soy\r\nValiente seré, yo sé\r\nMi esperanza está en Él\r\n\r\nSe oirá\r\nEn los cielos\r\nEl sonido de\r\nNuestra adoración\r\nLas murallas\r\nCaen a sus pies\r\nAl oír su voz\r\nPor su gracia\r\nÉl nos limpió\r\nCuán bueno es Dios\r\nSu nombre es Cristo\r\n\r\nSe oirá\r\nEn los cielos\r\nEl sonido de\r\nNuestra adoración\r\nLas murallas\r\nCaen a sus pies\r\nAl oír su voz\r\nPor su gracia\r\nÉl nos limpió\r\nCuán bueno es Dios\r\nSu nombre es Cristo\r\n\r\nSe oirá\r\nEn los cielos\r\nEl sonido de\r\nNuestra adoración\r\nLas murallas\r\nCaen a sus pies\r\nAl oír su voz\r\nPor su gracia\r\nÉl nos limpió\r\nCuán bueno es Dios\r\nSu nombre es Cristo\r\n\r\nSe oirá\r\nEn los cielos\r\nEl sonido de\r\nNuestra adoración\r\nLas murallas\r\nCaen a sus pies\r\nAl oír su voz\r\nPor su gracia\r\nÉl nos limpió\r\nCuán bueno es Dios\r\nSu nombre es Cristo\r\n\r\nCristo\r\nEl que salva\r\nLa esperanza\r\nEstá en Él\r\nCristo\r\nLuz del cielo\r\nRey eterno\r\nAmigo fiel"},
{"id":"116","titulo":"Juntos sintiendo lo mismo","letra":"Juntos sintiendo lo mismo,\r\nunidos por Cristo Jesús.\r\nCaminando hacia un destino,\r\nel Señor es el camino,\r\nque nos lleva hacia la meta eternal\r\n\r\nJuntos amándonos todos, \r\ncomo nos ama el Señor.\r\nPerdonando las ofensas,\r\ncompartiendo los momentos,\r\nde alegrías y tristezas por igual."},
{"id":"117","titulo":"Justificados pues por la fe ","letra":"Romanos 5:1\r\n\r\nJustificados pues por la fe \r\ntenemos paz para con Dios,\r\npor medio de nuestro Señor. \r\nJesucristo el Rey.\r\n\r\nPor quién también tenemos entrada por la fe,\r\na esa gracia en la cual estamos firmes.\r\n\/\/ Y nos gloriamos en la esperanza \r\nde la gloria de Dios,\r\ny no sólo eso sino también en la tribulación. \/\/"},
{"id":"118","titulo":"La alegría está en el corazón ","letra":"La alegría está en el corazón \r\nde aquel que conoce a Jesús.\r\nLa verdadera paz está en aquel \r\nque ya conoce a Jesús.\r\nOh sentimiento más precioso \r\nque viene del Señor,\r\nes el amor de aquel que ya conoce a Jesús.\r\n\r\n¡Aleluya! ¡Aleluya! ¡Aleluya! ¡Aleluya!\r\nOh sentimiento más precioso \r\nque viene del Señor,\r\nes el amor de aquel que ya conoce a Jesús."},
{"id":"119","titulo":"La Luna entristeció El Sol se apagó","letra":"La Luna entristeció El Sol se apagó\r\nCayó El Salvador del mundo\r\n\r\nSu cuerpo en la cruz\r\nSu sangre derramó\r\nEl peso del pecado sobre Él\r\n\r\nAl fin Él suspiró\r\nEl cielo lo ignoró\r\nEl hijo descendió en tinieblas\r\n\r\nLa guerra en el seol\r\nLa muerte derrotó\r\nEl infierno fue al fin vencido\r\n\r\nLa tierra retumbó\r\nLa piedra Él quitó\r\nSu amor perfecto siempre vencerá\r\n\r\nEl Rey resucitó\r\nLa muerte derrotó\r\nGanando la victoria\r\n\r\nPor siempre a Él la gloria es\r\nPor siempre exaltado es\r\nPor siempre Él es digno\r\nVivo está, vivo está\r\n\r\nLa tierra retumbó\r\nLa piedra Él quitó\r\nSu amor perfecto siempre vencerá\r\n\r\nEl Rey resucitó\r\nLa muerte derrotó\r\nGanando la victoria\r\n\r\nPor siempre a Él la gloria es\r\nPor siempre exaltado es\r\nPor siempre Él es digno\r\nVivo está, vivo está\r\n\r\nCanto aleluya\r\nCanto aleluya\r\nCanto aleluya\r\nEl cordero ya venció\r\n\r\nPor siempre a Él la gloria es\r\nPor siempre exaltado es\r\nPor siempre Él es digno\r\nVivo está, vivo está"},
{"id":"120","titulo":"La sangre de Jesús me redimió (Por mi murió)","letra":"La sangre de Jesús me redimió\r\nMe perdonó y libertad me dio\r\nTu majestad esta dentro de mí\r\nPor siempre creo en Ti\r\nPor siempre creo en TI\r\n\r\nMe inundas con justicia y amor\r\nTu gracia cautivó mi corazón\r\nTu Espíritu me guía a la verdad\r\nTu amor no fallará\r\nTu amor no fallará\r\n\r\nPor amor Dios dio su hijo único Jesús\r\nPor mí murió me dio esperanza y salvación\r\nEn mi lugar su vida entregó en la cruz\r\nMe amo, me amo\r\nAún sin merecerlo"},
{"id":"121","titulo":"La sangre que en la cruz vertió ","letra":"La sangre que en la cruz vertió \r\nfue por ti y para mí.\r\nLa sangre que me da la fuerza día a día \r\njamás perderá poder.\r\n\r\nAlcanza las más altas cumbres \r\ny fluye hasta el valle profundo.\r\nLa sangre que me da la fuerza día a día \r\njamás perderá poder."},
{"id":"122","titulo":"La única razón de mi adoración","letra":"La única razón de mi adoración, \r\neres Tu mi Jesús.\r\nEl único motivo para vivir, \r\neres tu mi Señor.\r\n\r\nLa única verdad está en Ti, \r\neres mi luz y mi salvación.\r\nMi único amor, eres tu Señor, \r\ny por siempre te alabaré.\r\n\r\nTu eres Todo Poderoso, \r\neres Santo y Majestuoso.\r\nEres fuerte, invencible, \r\ny no hay nadie como Tu."},
{"id":"123","titulo":"Las cadenas de la muerte me quitó","letra":"Las cadenas de la muerte me quitó\r\nPara mí, ya no hay condenación\r\nHay libertad, libertad\r\n\r\nSiendo esclavo del pecado me libró\r\nEn la cruz compró mi redención\r\nY libertad, libertad\r\n\r\nRompió mis cadenas, me dio vida nueva\r\nY al fondo del mar echó mi maldad\r\nLavó mis pecados, y me ha perdonado\r\nSolo en el nombre de Jesús hay libertad\r\n\r\nYo proclamo al que en la cruz por mí murió\r\nY cambió mi duro corazón\r\nPor libertad, libertad\r\n\r\nEl poder de su evangelio me salvó\r\nY no me avergüenzo del Señor\r\nMi libertad, libertad\r\n\r\nRompió mis cadenas, me dio vida nueva\r\nY al fondo del mar echó mi maldad\r\nLavó mis pecados, y me ha perdonado\r\nSolo en el nombre de Jesús hay libertad\r\n\r\nAl que el Hijo, hace libre, es libre en verdad\r\nAl que el Hijo, hace libre, es libre en verdad\r\n\r\n\/Rompió mis cadenas, me dio vida nueva\r\nY al fondo del mar echó mi maldad\r\nLavó mis pecados, y me ha perdonado\r\nSolo en el nombre de Jesús hay libertad\/\r\nHay libertad"},
{"id":"124","titulo":"Majestad, gloria a su Majestad","letra":"¡Majestad, gloria a su Majestad! \r\nJesucristo merece todo honor.\r\nMajestad, reino y autoridad. \r\nSuyo el honor, suyo el poder ¡gloria a Él!\r\n\r\nExaltad, engrandeced, su santo nombre.\r\nAdorad, magnificad, a Cristo el Rey.\r\n¡Majestad, gloria a su majestad!\r\n\/\/ Cristo murió, resucitó, y hoy es Señor. \/\/"},
{"id":"125","titulo":"Maravilloso Dios, Tú permaneces siempre fiel","letra":"Maravilloso Dios, Tú permaneces siempre fiel.\r\nTu gloria y tu poder llenan mi vida de tu ser.\r\nSostenme con tu amor, \r\ncon la victoria y tu perdón,\r\ndesde mi corazón, te canto hoy."},
{"id":"126","titulo":"Mas el Dios de toda gracia","letra":"2ªPedro 5:10\r\n\r\nMas el Dios de toda gracia \r\nque nos llamó a su gloria eterna\r\nos perfeccione y afirme, \r\nfortalezca y establezca.\r\n\/\/ A Él sea la gloria, a Él sea el imperio \r\npor los siglos de los siglos. \/\/\r\nAmén, amén, amén, si amén"},
{"id":"127","titulo":"Me gusta estar en tu casa ","letra":"Me gusta estar en tu casa \r\ncelebrando con tu pueblo.\r\nMe gusta darte honor \r\ncon mis manos y mi voz.\r\n\r\nRecíbela, recíbela \r\nla alabanza que te canto,\r\nRecíbela, recíbela \r\nde adentro de mi corazón.\r\n\r\nTú eres omnipotente, no hay otro como Tú.\r\nCuan grandes son tus obras, te amo mi Jesús."},
{"id":"128","titulo":"Me hace bien cada vez que me encuentro y canto","letra":"Me hace bien cada vez que me encuentro \r\ny canto con el pueblo de Cristo.\r\nMe hace bien cada vez que me encuentro \r\ny canto con el pueblo de Cristo.\r\n\r\nQue feliz que se ve cada hermano \r\ndando gloria a Dios, y siempre alabando.\r\nMe hace bien cada vez que me encuentro \r\ny canto con el pueblo de Cristo."},
{"id":"129","titulo":"Me has tomado en tus brazos","letra":"Salmos 73:23-24\r\n\r\nMe has tomado en tus brazos \r\ny me has dado salvación,\r\nde tu amor has derramado en mi corazón,\r\nNo sabré agradecerte lo que has hecho por mi,\r\nsolo puedo darte ahora mi canción,\r\n\r\nYo te doy gracias,\r\ngracias Señor, gracias mi Señor Jesús,\r\nGracias, muchas gracias señor, \r\noh gracias mi Señor Jesús\r\n\r\nEn la cruz diste tu vida,\r\nentregaste todo ahí, \r\nvida eterna regalaste al morir.\r\nPor tu sangre tengo entrada \r\nante el Trono Celestial,\r\npuedo entrar confiadamente ante Tí\r\n\r\nPara darte las gracias, gracias Señor,\r\noh gracias mi Señor Jesús,\r\ngracias Señor, gracias, muchas gracias señor,\r\noh gracias mi Señor Jesús."},
{"id":"130","titulo":"Me hirió el pecado, fui a Jesús (Himno 416)","letra":"Me hirió el pecado, fui a Jesús,\r\nMostréle mi dolor:\r\nPerdido, errante, vi su luz,\r\nBendíjome en su amor.\r\n\r\nEn la cruz, en la cruz,\r\nDo primero vi la luz.\r\nY las manchas de mi alma yo lavé;\r\nFue allí por la fe, do vi a Jesús\r\nY siempre feliz con él seré.\r\n\r\nEn una cruz, mi salvador\r\nSu sangre derramó\r\nPor este pobre pecador,\r\nA quien así salvó.\r\n\r\nVenció la muerte: ¡qué placer!\r\nY el padre lo exalto;\r\nEspero sólo en su poder;\r\nMorir no temo yo.\r\n\r\nAunque él se fue, conmigo está\r\nEl gran consolador;\r\nPor él entrada tengo ya\r\nAl reino del Señor.\r\n\r\nVivir en Cristo trae la paz;\r\nCon él habitaré.\r\nYa suyo soy, y de hoy en más \r\nA nadie temeré."},
{"id":"131","titulo":"Mejor es un día en la casa de Dios","letra":"Mejor es un día en la Casa de Dios,\r\nque mil años lejos de El.\r\nPrefiero un rincón en la casa de Dios,\r\n\/\/ que todo el palacio de un rey. \/\/\r\n\r\nVen conmigo a la Casa de Dios.\r\nCelebraremos juntos su amor.\r\nHaremos fiesta en honor \r\nde Aquél que nos amó.\r\nEstando aqui en la casa de Dios,\r\nAlegraremos su corazón, \r\nle brindaremos ofrendas,\r\nde obediencia y amor.\r\nEn la Casa de Dios.\r\n\r\nArde mi alma, arde mi amor,\r\npor Aquél que me dió la vida.\r\nPor eso le anhela mi corazón,\r\n\/\/ anhela de su compañía. \/\/"},
{"id":"132","titulo":"Mi alma se saciará","letra":"Salmos 63:1\r\n\r\nMi alma se saciará \r\ntan sólo de tu amor y de tu verdad.\r\nEres Tú para mí, rocío matinal, consolador.\r\n\r\nDe mañana te adoraré \r\ny con mi canto te alabaré.\r\nAl ponerse el sol, mi voz elevaré por tu favor.\r\n\r\nEres todo en mi ser, \r\nmi apoyo, mi sostén y un amigo leal.\r\nEncontré salvación, ternura y protección \r\nen Ti Señor."},
{"id":"133","titulo":"Mi anhelo, es buscar de día y noche","letra":"Mi anhelo, es buscar de día y noche,\r\nde tu amor y la ternura de tu Espíritu, Señor.\r\nEn tu presencia hay plenitud de gozo,\r\nen tu presencia, delicias a tu diestra.\r\nPor siempre y para siempre me gozo\r\nen tu presencia"},
{"id":"134","titulo":"Mi creación es alabanza","letra":"Mi canción es alabanza \r\nque ofrezco a mi Dios.\r\nMi deseo es adorarle con sincera devoción.\r\nNo me importa como cante, sino la intención,\r\nes ahora adorarle con el corazón.\r\nCon el corazón.\r\n\r\nMi alabanza es un canto \r\nde agradecimiento a Dios. \r\ntodo lo que tengo es suyo, \r\nno merezco nada yo.\r\nSin embargo aunque me olvide \r\nÉl no me olvidará,\r\ny si me marcho muy lejos de mí no se irá. \r\nDe mí no se irá\r\n\r\nAdorarle no es fácil, no le puedo engañar.\r\nÉl sabe mis intenciones, \r\nÉl sabe si hay humildad.\r\nNo es cantarle solamente sino es sentir\r\ncon todo el ser su presencia, es con El vivir.\r\nEs con Él vivir."},
{"id":"135","titulo":"Mi Cristo, mi Rey","letra":"Mi Cristo, mi Rey. \r\nNadie es como Tu.\r\nToda mi vida, quiero exaltar,\r\nlas maravillas de tu amor.\r\n\r\nConsuelo, refugio.\r\nTorre de fuerza y poder.\r\nTodo mi ser, lo que yo soy,\r\nnunca cese de adorar.\r\n\r\nCante al Señor toda la creación.\r\nHonra y poder, majestad sean al Rey.\r\nMontes caerán y el mar rugirá\r\nal sonar de tu nombre.\r\nCanto con goza al mirar tu poder.\r\nPor siempre yo te amaré y diré:\r\nIncomparables promesas me das Señor."},
{"id":"136","titulo":"Mi Dios y Padre eterno Autor de la creación (El Credo)","letra":"Mi Dios y Padre eterno Autor de la creación, poderoso\r\nTu Espíritu intervino\r\nEl Verbo se encarnó\r\nCristo, tú salvas\r\n\r\nCreo en nuestro Dios, el Padre y en Su Hijo Cristo, el Rey\r\nCreo en el Espíritu Santo. Dios, tres en uno es\r\nCreo que resucitaste, que nos levantarás\r\nCreo en el Nombre de Jesucristo\r\n\r\nMi juez y mi abogado Sufriste en la cruz\r\nMe has perdonado\r\nBajaste a las tinieblas Y en gloria y en poder te levantaste\r\n\r\nCreo en nuestro Dios, el Padre y en Su Hijo Cristo, el Rey\r\nCreo en el Espíritu Santo. Dios, tres en uno es\r\nCreo que resucitaste, que nos levantarás\r\nCreo en el Nombre de Jesucristo\r\n\r\n¡Creo en ti, Jesús!\r\n¡Creo que tú vivo estás!\r\n¡Creo que Jesús es el Señor!\r\n\r\nCreo en nuestro Dios, el Padre\r\nY en Su Hijo Cristo, el Rey\r\nCreo en el Espíritu Santo\r\nDios, tres en uno es\r\nCreo que resucitaste, que nos levantarás\r\n¡Creo en el Nombre de Jesucristo!\r\n\r\nCreo en la vida eterna\r\nCreo en la comunión\r\nCreo que tu pueblo es uno\r\nCreo en tu Iglesia, Dios\r\nCreo que resucitaremos y en gloria volverás\r\n¡Creo en el Nombre de Jesucristo!\r\n\r\nCreo en nuestro Dios, el Padre\r\nY en Su Hijo, Cristo el Rey\r\nCreo en el Espíritu Santo\r\nDios, tres en uno es\r\nCreo que resucitaste, que nos levantarás\r\n¡Creo en el Nombre de Jesucristo!\r\n¡Creo en el Nombre de Jesucristo!"},
{"id":"137","titulo":"Mi pensamiento eres Tú, Señor","letra":"Mi pensamiento eres Tú, Señor, \r\nmi pensamiento eres Tú.\r\nMi pensamiento eres Tú, Señor, \r\nmi pensamiento eres Tú.\r\n\r\nPorque Tú, me has dado la vida, \r\nporque Tú, me has dado el existir,\r\nporque Tú, me has dado cariño, \r\nme has dado amor."},
{"id":"138","titulo":"Mi primer amor eres Tú Jesús","letra":"Mi primer amor eres Tú Jesús, \r\nmi alma anhela agradarte.\r\nMi primer amor eres Tú Jesús, \r\nmi alma anhela agradarte.\r\n\/\/ Quiero ser fiel a Ti Señor, \r\nquiero ser todo lo que esperas de mí,\r\ny no amarte de palabra, sino de verdad. \/\/\r\nsino de verdad, sino de verdad."},
{"id":"139","titulo":"Mi vergüenza me sepultó (Glorioso día)","letra":"Mi vergüenza me sepultó \r\nYo buscaba un salvador\r\nMas tu perdón, me liberó\r\n\r\nMuerto estaba en mi interior\r\nMe escondía de Ti, Señor\r\nMas tu perdón, me liberó\r\n\r\nTu voz me habló\r\nY a la muerte venció\r\nGlorioso día, tu sangre me rescató\r\nTu voz me habló\r\nY a la muerte venció\r\nGlorioso día, tu sangre me rescató\r\n\r\nAhora libre soy en tu amor\r\nEs tu gracia la que me sanó\r\nMas tu perdon, a mí me liberó\r\n\r\nTu voz me habló\r\nY a la muerte venció\r\nGlorioso día, tu sangre me rescató\r\nTu voz me habló\r\nY a la muerte venció\r\nGlorioso día, tu sangre me rescató\r\n\r\nDe mi pecado me rescataste\r\nEn tu gloria cadenas se rompen\r\nVivía solo y sin consuelo\r\nAhora soy ciudadano del cielo\r\n\r\nTú me sanaste estando herido\r\nJesús por tu amor yo respiro\r\nTengo futuro, ahora veo\r\nPorque tu voz me habló\r\n\r\nY a la muerte venció\r\nGlorioso día, tu sangre me rescató\r\nTu voz me habló\r\nY a la muerte venció\r\nGlorioso día, tu sangre me rescató"},
{"id":"140","titulo":"Mil veces te fallé, más tú fuiste fiel\r\n","letra":"Mil veces te fallé, más Tu fuiste fiel.\r\nTu gracia me levantó, me basta tu amor.\r\nDios eterno, tu luz por siempre brillará, \r\ny tu gloria, incomparable y sin final. \r\nSeñor tu voluntad permanecerá. \r\nEn Tí me quiero perder en adoración. \r\nDios eterno, tu luz por siempre brillará, \r\ny tu gloria, incomparable y sin final. \r\n\r\nDe mi corazón te doy el control, \r\nconsume todo mi interior. \r\nTu justicia y amor me abrazan Señor. \r\nTe amo desde mi interior. \r\n\r\nSeñor tu voluntad permanecerá. \r\nEn Ti me quiero perder en adoración. \r\nDios eterno, tu luz por siempre brillará, \r\ny tu gloria, incomparable y sin final. \r\n\r\nDe mi corazón te doy el control, \r\nconsume todo mi interior. \r\nTu justicia y amor me abrazan Señor. \r\nte amo desde mi interior. \r\nDios eterno, tu luz por siempre brillará, \r\ny tu gloria, incomparable y sin final. \r\nEl clamor de mi ser es contigo estar. \r\nDesde mi interior mi alma clamará. "},
{"id":"141","titulo":"Mira Señor Jesús","letra":"Mira Señor Jesús, \r\néste es tu pueblo y quiere amarte,\r\nviene a ofrecerte hoy todo su amor.\r\nHoy no viene a buscar, sólo viene a entregar.\r\nMira Señor Jesús, sólo te quiere alabar."},
{"id":"142","titulo":"Muéstrame tus caminos oh Señor","letra":"Salmos 25:4– 5\r\n\r\nMuéstrame tus caminos oh Señor, \r\ny enséñame tus sendas mi Señor.\r\nEncamíname en tu verdad y enséñame \r\nporque Tú eres el Dios de mi salvación.\r\n\r\nEn Ti he esperado, en Ti esperaré. \r\nTodo el día y cada noche,\r\nmuy temprano en la mañana. \r\nEnséñame a esperar en Ti. En Ti Señor."},
{"id":"143","titulo":"Muy poco falta ya ","letra":"Muy poco falta ya (muy poco falta ya),\r\nmuy pronto volverás (muy pronto volverás).\r\nY nuestro corazón (y nuestro corazón),\r\nno deja de alabar (no deja de alabar).\r\nAquí estoy Señor (aquí estoy Señor),\r\nte espero en mi lugar (te espero en mi lugar).\r\nYa vendrás (ya vendrás)\r\na llevar (a llevar)\r\ntu iglesia al hogar (tu iglesia al hogar)."},
{"id":"144","titulo":"Nadie como Tu","letra":"Nadie como Tú, \r\nnadie más llena mi ser como Tú.\r\nPor la eternidad podría buscar, \r\nmás no hay nadie como Tú."},
{"id":"145","titulo":"No existe bien para mí que esté fuera de ti","letra":"Salmos 16:2\r\n\r\nNo existe bien para mí que esté fuera de ti,\r\ngracias Dios mío, me siento feliz.\r\nCuán dulce amor Tú me diste, \r\nme asombras Señor,\r\ny hoy quiero darte lo poco que soy.\r\nPuedo sentir en el viento, la lluvia y el sol,\r\nque cada día me muestras tu amor.\r\nComo la arena en el mar, las aves al cantar\r\ny la pureza de un manantial.\r\nAsí eres dulce Jesús cuando me das tu amor,\r\ngracias Señor, gracias Señor, gracias Señor."},
{"id":"146","titulo":"No existen más motivos, Señor","letra":"Filipenses 2: 10-11\r\n\r\nNo existen más motivos, Señor.\r\nVenimos hoy rendidos a Ti.\r\nLa única razón de nuestra adoración hoy, \r\neres Tú.\r\nElevamos olor fragante para Ti, para Ti.\r\n \r\nSólo a Ti sea la gloria, Señor,\r\nLa alabanza y la adoración,\r\nque toda lengua confiese que Tu eres el Señor.\r\nSólo a Ti sea la gloria, Señor.\r\nLa alabanza y la adoración,\r\nQue toda rodilla se postre, \r\nante el único Rey y Dios."}
    // Otras canciones aquí...
  ];

  const paginacion = 30;
  const cuenta1 = currentPage * paginacion;
  const cuenta2 = cuenta1 - paginacion;
  const resultado = canciones.slice(cuenta2, cuenta1);

  const prev = () => {
    setCurrentPage((prevPage) => prevPage - 1);
  };

  const next = () => {
    setCurrentPage((prevPage) => prevPage + 1);
  };

  const handleLetra = (titulo) => {
    const cancionSeleccionada = canciones.find(
      (cancion) =>
        cancion.titulo === titulo || cancion.id === titulo // Buscar por título o por ID
    );
    if (cancionSeleccionada) {
      setLlave(true);
      setLetra(cancionSeleccionada.letra);
      setTituloCancionSeleccionada(cancionSeleccionada.titulo);
    }
  };
  
  const handleBusqueda = (event) => {
    setBusqueda(event.target.value);
  };

  const handleSubmit = (event) => {
    event.preventDefault();
    
    // Verificar si la búsqueda es un número
    const esNumero = !isNaN(busqueda);
  
    // Si es un número, buscar por ID
    if (esNumero) {
      const cancionPorId = canciones.find((cancion) => cancion.id === busqueda);
      if (cancionPorId) {
        setResultadoBusqueda([cancionPorId]);
        setLlave(true);
        setLetra(cancionPorId.letra);
        setTituloCancionSeleccionada(cancionPorId.titulo);
      } else {
        setResultadoBusqueda([]);
        setLlave(false);
        setLetra([]);
        setTituloCancionSeleccionada("Canción no encontrada");
      }
    } else {
      // Buscar por título
      const resultadosPorTitulo = canciones.filter((cancion) =>
        cancion.titulo.toLowerCase().includes(busqueda.toLowerCase())
      );
  
      // Si se encontraron resultados por título, mostrarlos
      if (resultadosPorTitulo.length > 0) {
        setResultadoBusqueda(resultadosPorTitulo);
  
        // Si hay solo un resultado en la búsqueda, mostrar automáticamente la letra
        if (resultadosPorTitulo.length === 1) {
          const cancionSeleccionada = resultadosPorTitulo[0];
          setLlave(true);
          setLetra(cancionSeleccionada.letra);
          setTituloCancionSeleccionada(cancionSeleccionada.titulo);
        }
      } else {
        // Buscar por contenido de la letra
        const resultadosPorLetra = canciones.filter((cancion) =>
          cancion.letra.toLowerCase().includes(busqueda.toLowerCase())
        );
  
        // Si se encontraron resultados por letra, mostrarlos
        if (resultadosPorLetra.length > 0) {
          setResultadoBusqueda(resultadosPorLetra);
  
          // Si hay solo un resultado en la búsqueda, mostrar automáticamente la letra
          if (resultadosPorLetra.length === 1) {
            const cancionSeleccionada = resultadosPorLetra[0];
            setLlave(true);
            setLetra(cancionSeleccionada.letra);
            setTituloCancionSeleccionada(cancionSeleccionada.titulo);
          }
        } else {
          // Si no se encontraron resultados, mostrar mensaje
          setResultadoBusqueda([]);
          setLlave(false);
          setLetra([]);
          setTituloCancionSeleccionada("Canción no encontrada");
        }
      }
    }
  };
  
  
  
  const volverAtras = () => {
    setLlave(false);
    setLetra([]);
    setTituloCancionSeleccionada("");
  };


  let versos = [];
  if (llave) {
    versos = letra.split("\n");
  }

  return (
    <div className="container-cancionero">
      <h1 className="titulo-cancionero">Cancionero</h1>
      <div className="container-buscador">
        <form onSubmit={handleSubmit} className="form-buscador">
          <input
            type="text"
            className="buscador"
            placeholder="Buscar canción..."
            value={busqueda}
            onChange={handleBusqueda}
          />
          <button type="submit" className="button-submit">
            <i className="fa-solid fa-magnifying-glass icono-buscador"></i>
          </button>
        </form>

        {/* FILTRO
        <select name="" id="filtro" className="filtro">
          <option value="Todos" className="options">
            Todos
          </option>
          <option value="Coros" className="options">
            Coros
          </option>
          <option value="Himnos" className="options">
            Himnos
          </option>
        </select> */}


      </div>
      {!llave ? (
        <>
          <div className="container-titulo-indice">
            <h2 className="titulo-indice">
              <b className="txt-indice">Indice de Canciones</b>
            </h2>
          </div>
          <div className="container-indice-canciones">
            {(resultadoBusqueda.length > 0 ? resultadoBusqueda : resultado).map(
              (cancion) => (
                <div className="container-indice" key={cancion.id}>
                  <a
                    href="#"
                    onClick={() => handleLetra(cancion.titulo)}
                    className="link-canciones"
                  >
                    {cancion.id}_{cancion.titulo}
                  </a>
                </div>
              )
            )}
          </div>
          <div className="container-buttons-paginacion">
            <p>Siguiente página</p>
            <button
              onClick={prev}
              disabled={currentPage === 1}
              className="buttons-paginacion"
            >
              <i className="fa-solid fa-chevron-left"></i>
            </button>
            <button
              onClick={next}
              disabled={cuenta1 >= canciones.length}
              className="buttons-paginacion"
            >
              <i className="fa-solid fa-chevron-right"></i>
            </button>
            <p>Página anterior</p>
          </div>
        </>
      ) : (
        <div className="container-letra">
          <button onClick={volverAtras} className="button-volver">
            <i className="fa-solid fa-circle-arrow-left icono-volver"></i>
          </button>
          <h1 className="titulo-cancion-select">{tituloCancionSeleccionada}</h1>
          {versos.map((verso, index) => {
            if (verso.startsWith("/est")) {
              return (
                <div key={index} className="texto-estrofa">
                  <p>{verso.replace("/est", "")}</p>
                </div>
              );
            } else if (verso.startsWith("/es")) {
              return (
                <div key={index} className="texto-estribillo">
                  <p>{verso.replace("/es", "")}</p>
                </div>
              );
            } else {
              return (
                <div key={index} className="parte-cancion">
                  <p className="texto-letra-general">{verso}</p>
                </div>
              );
            }
          })}
        </div>
      )}
      <Footer></Footer>
    </div>
  );
};

export default Cancionero;
